// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Network enums.
type Network int32

const (
	Network_NETWORK_UNSPECIFIED Network = 0
	Network_NETWORK_ETHERNET    Network = 1
	Network_NETWORK_WIFI        Network = 2
	Network_NETWORK_CELLULAR    Network = 3
)

var Network_name = map[int32]string{
	0: "NETWORK_UNSPECIFIED",
	1: "NETWORK_ETHERNET",
	2: "NETWORK_WIFI",
	3: "NETWORK_CELLULAR",
}

var Network_value = map[string]int32{
	"NETWORK_UNSPECIFIED": 0,
	"NETWORK_ETHERNET":    1,
	"NETWORK_WIFI":        2,
	"NETWORK_CELLULAR":    3,
}

func (x Network) Enum() *Network {
	p := new(Network)
	*p = x
	return p
}

func (x Network) String() string {
	return proto.EnumName(Network_name, int32(x))
}

func (x *Network) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_value, data, "Network")
	if err != nil {
		return err
	}
	*x = Network(value)
	return nil
}

func (Network) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

// Platform enum type.
type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_H5          Platform = 1
	Platform_PLATFORM_WEB         Platform = 2
	Platform_PLATFORM_CHROME      Platform = 3
	Platform_PLATFORM_LINUX       Platform = 4
	Platform_PLATFORM_WINDOWS     Platform = 5
	Platform_PLATFORM_DARWIN      Platform = 6
	Platform_PLATFORM_ANDROID     Platform = 7
	Platform_PLATFORM_IOS         Platform = 8
	Platform_PLATFORM_SERVER      Platform = 9
)

var Platform_name = map[int32]string{
	0: "PLATFORM_UNSPECIFIED",
	1: "PLATFORM_H5",
	2: "PLATFORM_WEB",
	3: "PLATFORM_CHROME",
	4: "PLATFORM_LINUX",
	5: "PLATFORM_WINDOWS",
	6: "PLATFORM_DARWIN",
	7: "PLATFORM_ANDROID",
	8: "PLATFORM_IOS",
	9: "PLATFORM_SERVER",
}

var Platform_value = map[string]int32{
	"PLATFORM_UNSPECIFIED": 0,
	"PLATFORM_H5":          1,
	"PLATFORM_WEB":         2,
	"PLATFORM_CHROME":      3,
	"PLATFORM_LINUX":       4,
	"PLATFORM_WINDOWS":     5,
	"PLATFORM_DARWIN":      6,
	"PLATFORM_ANDROID":     7,
	"PLATFORM_IOS":         8,
	"PLATFORM_SERVER":      9,
}

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return proto.EnumName(Platform_name, int32(x))
}

func (x *Platform) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Platform_value, data, "Platform")
	if err != nil {
		return err
	}
	*x = Platform(value)
	return nil
}

func (Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

// Request metadata.
type Metadata struct {
	Account              *uint64   `protobuf:"varint,1,req,name=account" json:"account,omitempty"`
	Token                *string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Platform             *Platform `protobuf:"varint,3,req,name=platform,enum=appootb.common.Platform" json:"platform,omitempty"`
	Network              *Network  `protobuf:"varint,4,opt,name=network,enum=appootb.common.Network" json:"network,omitempty"`
	Package              *string   `protobuf:"bytes,5,opt,name=package" json:"package,omitempty"`
	Version              *string   `protobuf:"bytes,6,req,name=version" json:"version,omitempty"`
	OsVersion            *string   `protobuf:"bytes,7,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	Brand                *string   `protobuf:"bytes,8,opt,name=brand" json:"brand,omitempty"`
	Model                *string   `protobuf:"bytes,9,opt,name=model" json:"model,omitempty"`
	DeviceId             *string   `protobuf:"bytes,10,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Timestamp            *int64    `protobuf:"varint,11,req,name=timestamp" json:"timestamp,omitempty"`
	IsEmulator           *bool     `protobuf:"varint,12,opt,name=is_emulator,json=isEmulator,def=1" json:"is_emulator,omitempty"`
	Latitude             *string   `protobuf:"bytes,13,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            *string   `protobuf:"bytes,14,opt,name=longitude" json:"longitude,omitempty"`
	Locale               *string   `protobuf:"bytes,15,opt,name=locale" json:"locale,omitempty"`
	ClientIp             *string   `protobuf:"bytes,16,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	Channel              *string   `protobuf:"bytes,17,opt,name=channel" json:"channel,omitempty"`
	Product              *string   `protobuf:"bytes,18,opt,name=product" json:"product,omitempty"`
	TraceId              *string   `protobuf:"bytes,19,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	IsDebug              *bool     `protobuf:"varint,20,opt,name=is_debug,json=isDebug,def=0" json:"is_debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

const Default_Metadata_IsEmulator bool = true
const Default_Metadata_IsDebug bool = false

func (m *Metadata) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *Metadata) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Metadata) GetPlatform() Platform {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (m *Metadata) GetNetwork() Network {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return Network_NETWORK_UNSPECIFIED
}

func (m *Metadata) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

func (m *Metadata) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Metadata) GetOsVersion() string {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return ""
}

func (m *Metadata) GetBrand() string {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return ""
}

func (m *Metadata) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Metadata) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *Metadata) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Metadata) GetIsEmulator() bool {
	if m != nil && m.IsEmulator != nil {
		return *m.IsEmulator
	}
	return Default_Metadata_IsEmulator
}

func (m *Metadata) GetLatitude() string {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return ""
}

func (m *Metadata) GetLongitude() string {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return ""
}

func (m *Metadata) GetLocale() string {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return ""
}

func (m *Metadata) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *Metadata) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *Metadata) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *Metadata) GetTraceId() string {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return ""
}

func (m *Metadata) GetIsDebug() bool {
	if m != nil && m.IsDebug != nil {
		return *m.IsDebug
	}
	return Default_Metadata_IsDebug
}

func init() {
	proto.RegisterEnum("appootb.common.Network", Network_name, Network_value)
	proto.RegisterEnum("appootb.common.Platform", Platform_name, Platform_value)
	proto.RegisterType((*Metadata)(nil), "appootb.common.Metadata")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xcd, 0x6e, 0xdb, 0x38,
	0x14, 0x85, 0x47, 0xf2, 0x9f, 0xcc, 0x24, 0x0e, 0x87, 0x31, 0x26, 0x9c, 0x99, 0x16, 0x10, 0x0a,
	0x04, 0x30, 0xb2, 0xb0, 0xd1, 0xa0, 0xdd, 0x74, 0xe7, 0x1f, 0x05, 0x16, 0xea, 0xc8, 0x06, 0xed,
	0xc4, 0x45, 0x11, 0xc0, 0xa5, 0x25, 0xc6, 0x11, 0x22, 0x89, 0x82, 0x44, 0x25, 0xef, 0xd3, 0x65,
	0x1f, 0xa5, 0x4f, 0xd0, 0x07, 0xe8, 0x43, 0x74, 0x59, 0x88, 0x94, 0x94, 0x3a, 0xcb, 0xf3, 0x9d,
	0x73, 0x79, 0xc9, 0x2b, 0x5d, 0xd0, 0x09, 0x99, 0xa0, 0x1e, 0x15, 0xb4, 0x1f, 0x27, 0x5c, 0x70,
	0xd4, 0xa1, 0x71, 0xcc, 0xb9, 0xd8, 0xf6, 0x5d, 0x1e, 0x86, 0x3c, 0x7a, 0xf3, 0xb3, 0x0e, 0x8c,
	0xab, 0x22, 0x82, 0x30, 0x68, 0x51, 0xd7, 0xe5, 0x59, 0x24, 0xb0, 0x66, 0xea, 0xbd, 0x3a, 0x29,
	0x25, 0xea, 0x82, 0x86, 0xe0, 0x0f, 0x2c, 0xc2, 0xba, 0xa9, 0xf5, 0xda, 0x44, 0x09, 0xf4, 0x0e,
	0x18, 0x71, 0x40, 0xc5, 0x1d, 0x4f, 0x42, 0x5c, 0x33, 0xf5, 0x5e, 0xe7, 0x02, 0xf7, 0xf7, 0xcf,
	0xef, 0x2f, 0x0a, 0x9f, 0x54, 0x49, 0xf4, 0x16, 0xb4, 0x22, 0x26, 0x9e, 0x78, 0xf2, 0x80, 0xeb,
	0xa6, 0xd6, 0xeb, 0x5c, 0x9c, 0xbe, 0x2c, 0x72, 0x94, 0x4d, 0xca, 0x5c, 0x7e, 0xb1, 0x98, 0xba,
	0x0f, 0x74, 0xc7, 0x70, 0x43, 0x5e, 0xa0, 0x94, 0xb9, 0xf3, 0xc8, 0x92, 0xd4, 0xe7, 0x11, 0x6e,
	0x9a, 0x7a, 0xee, 0x14, 0x12, 0xbd, 0x06, 0x80, 0xa7, 0x9b, 0xd2, 0x6c, 0xc9, 0xb2, 0x36, 0x4f,
	0x6f, 0x0a, 0xbb, 0x0b, 0x1a, 0xdb, 0x84, 0x46, 0x1e, 0x36, 0xd4, 0x8b, 0xa4, 0xc8, 0x69, 0xc8,
	0x3d, 0x16, 0xe0, 0xb6, 0xa2, 0x52, 0xa0, 0xff, 0x41, 0xdb, 0x63, 0x8f, 0xbe, 0xcb, 0x36, 0xbe,
	0x87, 0x81, 0x6c, 0x63, 0x28, 0x60, 0x7b, 0xe8, 0x15, 0x68, 0x0b, 0x3f, 0x64, 0xa9, 0xa0, 0x61,
	0x8c, 0x0f, 0x4c, 0xbd, 0x57, 0x23, 0xcf, 0x00, 0x9d, 0x81, 0x03, 0x3f, 0xdd, 0xb0, 0x30, 0x0b,
	0xa8, 0xe0, 0x09, 0x3e, 0x34, 0xb5, 0x9e, 0xf1, 0xa1, 0x2e, 0x92, 0x8c, 0x11, 0xe0, 0xa7, 0x56,
	0xc1, 0xd1, 0x7f, 0xc0, 0x08, 0xa8, 0xf0, 0x45, 0xe6, 0x31, 0x7c, 0x24, 0x5b, 0x57, 0x3a, 0x6f,
	0x10, 0xf0, 0x68, 0xa7, 0xcc, 0x8e, 0x7a, 0x47, 0x05, 0xd0, 0x3f, 0xa0, 0x19, 0x70, 0x97, 0x06,
	0x0c, 0x1f, 0x4b, 0xab, 0x50, 0xf9, 0x9d, 0xdd, 0xc0, 0x67, 0x91, 0xd8, 0xf8, 0x31, 0x86, 0xea,
	0x48, 0x05, 0xec, 0x38, 0x9f, 0x9a, 0x7b, 0x4f, 0xa3, 0x88, 0x05, 0xf8, 0x6f, 0x35, 0xcf, 0x42,
	0xca, 0x49, 0x27, 0xdc, 0xcb, 0x5c, 0x81, 0x51, 0x31, 0x69, 0x25, 0xd1, 0xbf, 0xc0, 0x10, 0x09,
	0x55, 0x33, 0x38, 0x51, 0x96, 0xd4, 0xb6, 0x87, 0x4c, 0x60, 0xf8, 0xe9, 0xc6, 0x63, 0xdb, 0x6c,
	0x87, 0xbb, 0xf2, 0x85, 0x8d, 0x3b, 0x1a, 0xa4, 0x8c, 0xb4, 0xfc, 0x74, 0x92, 0xd3, 0xf3, 0x2f,
	0xa0, 0x55, 0x7c, 0x54, 0x74, 0x0a, 0x4e, 0x1c, 0x6b, 0xb5, 0x9e, 0x93, 0x8f, 0x9b, 0x6b, 0x67,
	0xb9, 0xb0, 0xc6, 0xf6, 0xa5, 0x6d, 0x4d, 0xe0, 0x5f, 0xa8, 0x0b, 0x60, 0x69, 0x58, 0xab, 0xa9,
	0x45, 0x1c, 0x6b, 0x05, 0x35, 0x04, 0xc1, 0x61, 0x49, 0xd7, 0xf6, 0xa5, 0x0d, 0xf5, 0x3f, 0x73,
	0x63, 0x6b, 0x36, 0xbb, 0x9e, 0x0d, 0x09, 0xac, 0x9d, 0xff, 0xd0, 0x80, 0x51, 0xfe, 0x6c, 0x08,
	0x83, 0xee, 0x62, 0x36, 0x5c, 0x5d, 0xce, 0xc9, 0xd5, 0x8b, 0x26, 0xc7, 0xe0, 0xa0, 0x72, 0xa6,
	0xef, 0xd5, 0xf9, 0x15, 0x58, 0x5b, 0x23, 0xa8, 0xa3, 0x13, 0x70, 0x5c, 0x91, 0xf1, 0x94, 0xcc,
	0xaf, 0x2c, 0x58, 0x43, 0x08, 0x74, 0x2a, 0x38, 0xb3, 0x9d, 0xeb, 0x4f, 0xb0, 0x9e, 0x5f, 0xe4,
	0xb9, 0xd4, 0x76, 0x26, 0xf3, 0xf5, 0x12, 0x36, 0xf6, 0xca, 0x27, 0x43, 0xb2, 0xb6, 0x1d, 0xd8,
	0xdc, 0x8b, 0x0e, 0x9d, 0x09, 0x99, 0xdb, 0x13, 0xd8, 0xda, 0xeb, 0x6d, 0xcf, 0x97, 0xd0, 0xd8,
	0x2b, 0x5e, 0x5a, 0xe4, 0xc6, 0x22, 0xb0, 0x3d, 0x7a, 0x02, 0xc8, 0xe5, 0xe1, 0x8b, 0x25, 0x19,
	0x1d, 0x95, 0x6b, 0xbb, 0xc8, 0x17, 0x7b, 0xaa, 0x2d, 0xb4, 0xcf, 0x67, 0x3b, 0x5f, 0xdc, 0x67,
	0x32, 0x31, 0x28, 0xd2, 0x03, 0xb9, 0xf6, 0xdb, 0xec, 0x6e, 0xb0, 0xe3, 0x03, 0x55, 0xf9, 0x4b,
	0xd3, 0xbe, 0xea, 0xb5, 0xf1, 0x62, 0xf4, 0x4d, 0x6f, 0x8e, 0x25, 0xf9, 0xae, 0x77, 0x87, 0x2a,
	0x7e, 0x2b, 0x0f, 0xbb, 0x55, 0xf8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x36, 0x0d, 0x62,
	0x3d, 0x04, 0x00, 0x00,
}
