// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: unique_id.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _unique_id_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on UniqueId with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UniqueId) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// UniqueIdValidationError is the validation error returned by
// UniqueId.Validate if the designated constraints aren't met.
type UniqueIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UniqueIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UniqueIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UniqueIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UniqueIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UniqueIdValidationError) ErrorName() string { return "UniqueIdValidationError" }

// Error satisfies the builtin error interface
func (e UniqueIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUniqueId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UniqueIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UniqueIdValidationError{}

// Validate checks the field values on UniqueIds with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UniqueIds) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// UniqueIdsValidationError is the validation error returned by
// UniqueIds.Validate if the designated constraints aren't met.
type UniqueIdsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UniqueIdsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UniqueIdsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UniqueIdsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UniqueIdsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UniqueIdsValidationError) ErrorName() string { return "UniqueIdsValidationError" }

// Error satisfies the builtin error interface
func (e UniqueIdsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUniqueIds.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UniqueIdsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UniqueIdsValidationError{}

// Validate checks the field values on UUID with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *UUID) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Uuid

	return nil
}

// UUIDValidationError is the validation error returned by UUID.Validate if the
// designated constraints aren't met.
type UUIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UUIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UUIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UUIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UUIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UUIDValidationError) ErrorName() string { return "UUIDValidationError" }

// Error satisfies the builtin error interface
func (e UUIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUUID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UUIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UUIDValidationError{}

// Validate checks the field values on UUIDs with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UUIDs) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// UUIDsValidationError is the validation error returned by UUIDs.Validate if
// the designated constraints aren't met.
type UUIDsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UUIDsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UUIDsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UUIDsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UUIDsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UUIDsValidationError) ErrorName() string { return "UUIDsValidationError" }

// Error satisfies the builtin error interface
func (e UUIDsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUUIDs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UUIDsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UUIDsValidationError{}

// Validate checks the field values on PaginationIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PaginationIdRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetTarget()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaginationIdRequestValidationError{
				field:  "Target",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Offset

	// no validation rules for Count

	return nil
}

// PaginationIdRequestValidationError is the validation error returned by
// PaginationIdRequest.Validate if the designated constraints aren't met.
type PaginationIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationIdRequestValidationError) ErrorName() string {
	return "PaginationIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PaginationIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationIdRequestValidationError{}

// Validate checks the field values on PaginationIdResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PaginationIdResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for More

	// no validation rules for Next

	if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaginationIdResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// PaginationIdResponseValidationError is the validation error returned by
// PaginationIdResponse.Validate if the designated constraints aren't met.
type PaginationIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationIdResponseValidationError) ErrorName() string {
	return "PaginationIdResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PaginationIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationIdResponseValidationError{}
