// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: unique_id.proto

package common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Unique ID (uint64 type).
type UniqueId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"` // ID value
}

func (x *UniqueId) Reset() {
	*x = UniqueId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueId) ProtoMessage() {}

func (x *UniqueId) ProtoReflect() protoreflect.Message {
	mi := &file_unique_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueId.ProtoReflect.Descriptor instead.
func (*UniqueId) Descriptor() ([]byte, []int) {
	return file_unique_id_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueId) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

// Unique IDs (uint64 array).
type UniqueIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,name=ids" json:"ids,omitempty"` // ID list
}

func (x *UniqueIds) Reset() {
	*x = UniqueIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIds) ProtoMessage() {}

func (x *UniqueIds) ProtoReflect() protoreflect.Message {
	mi := &file_unique_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIds.ProtoReflect.Descriptor instead.
func (*UniqueIds) Descriptor() ([]byte, []int) {
	return file_unique_id_proto_rawDescGZIP(), []int{1}
}

func (x *UniqueIds) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_unique_id_proto protoreflect.FileDescriptor

var file_unique_id_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x6f, 0x74, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x22, 0x1a, 0x0a, 0x08, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1d, 0x0a,
	0x09, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x42, 0x52, 0x0a, 0x12,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6f, 0x6f, 0x74, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x42, 0x0d, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x48, 0x01, 0x50, 0x01, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0xf8,
	0x01, 0x01, 0xa2, 0x02, 0x03, 0x43, 0x50, 0x42, 0xaa, 0x02, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0xca, 0x02, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_unique_id_proto_rawDescOnce sync.Once
	file_unique_id_proto_rawDescData = file_unique_id_proto_rawDesc
)

func file_unique_id_proto_rawDescGZIP() []byte {
	file_unique_id_proto_rawDescOnce.Do(func() {
		file_unique_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_unique_id_proto_rawDescData)
	})
	return file_unique_id_proto_rawDescData
}

var file_unique_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unique_id_proto_goTypes = []interface{}{
	(*UniqueId)(nil),  // 0: appootb.common.UniqueId
	(*UniqueIds)(nil), // 1: appootb.common.UniqueIds
}
var file_unique_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unique_id_proto_init() }
func file_unique_id_proto_init() {
	if File_unique_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unique_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unique_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unique_id_proto_goTypes,
		DependencyIndexes: file_unique_id_proto_depIdxs,
		MessageInfos:      file_unique_id_proto_msgTypes,
	}.Build()
	File_unique_id_proto = out.File
	file_unique_id_proto_rawDesc = nil
	file_unique_id_proto_goTypes = nil
	file_unique_id_proto_depIdxs = nil
}
