// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_code.proto

package captcha

import (
	context "context"
	fmt "fmt"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Captcha code verify request.
type VerifyRequest struct {
	Category             *Category `protobuf:"varint,1,req,name=category,enum=appootb.captcha.Category" json:"category,omitempty"`
	Target               *string   `protobuf:"bytes,2,req,name=target" json:"target,omitempty"`
	Value                *string   `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c4d6ed9b2e66a6, []int{0}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetCategory() Category {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (m *VerifyRequest) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *VerifyRequest) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "appootb.captcha.VerifyRequest")
}

func init() { proto.RegisterFile("inner_code.proto", fileDescriptor_b5c4d6ed9b2e66a6) }

var fileDescriptor_b5c4d6ed9b2e66a6 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcd, 0x4a, 0x2b, 0x31,
	0x14, 0x66, 0xd2, 0x7b, 0x7b, 0x6f, 0x03, 0xed, 0xbd, 0x8c, 0x5a, 0xea, 0x28, 0x5a, 0x0a, 0x4a,
	0x71, 0x91, 0x40, 0xc1, 0x8d, 0x3b, 0x3b, 0x08, 0xba, 0x2b, 0x5d, 0xb8, 0x90, 0xa2, 0xa4, 0x69,
	0x3a, 0x0d, 0x74, 0x72, 0x62, 0x26, 0x53, 0xa8, 0xb8, 0x10, 0x5f, 0xc1, 0x8d, 0x6b, 0x97, 0x3e,
	0x8a, 0x5b, 0x5f, 0xc1, 0x87, 0x70, 0x29, 0x33, 0x93, 0x29, 0x58, 0x97, 0xe7, 0x3b, 0x39, 0xdf,
	0x5f, 0xf0, 0x7f, 0xa9, 0x94, 0x30, 0x37, 0x1c, 0x26, 0x82, 0x68, 0x03, 0x16, 0xfc, 0x7f, 0x4c,
	0x6b, 0x00, 0x3b, 0x26, 0x9c, 0x69, 0xcb, 0x67, 0x2c, 0x68, 0x3b, 0x80, 0x6a, 0x61, 0x62, 0x99,
	0x24, 0x12, 0x14, 0x4d, 0x84, 0x59, 0x48, 0xee, 0x4e, 0x82, 0xdd, 0x08, 0x20, 0x9a, 0x0b, 0xca,
	0xb4, 0xa4, 0x4c, 0x29, 0xb0, 0xcc, 0x4a, 0x50, 0x89, 0xdb, 0xee, 0xb8, 0x6d, 0x3e, 0x8d, 0xd3,
	0x29, 0x15, 0xb1, 0xb6, 0x4b, 0xb7, 0xac, 0x4b, 0xc5, 0xe7, 0x69, 0x29, 0xde, 0xb1, 0xb8, 0x7e,
	0x29, 0x8c, 0x9c, 0x2e, 0x87, 0xe2, 0x36, 0x15, 0x89, 0xf5, 0x8f, 0xf1, 0x5f, 0xce, 0xac, 0x88,
	0xc0, 0x2c, 0x5b, 0x5e, 0x1b, 0x75, 0x1b, 0xbd, 0x6d, 0xb2, 0x66, 0x90, 0x84, 0xee, 0xc1, 0x70,
	0xf5, 0xd4, 0x6f, 0xe2, 0xaa, 0x65, 0x26, 0x12, 0xb6, 0x85, 0xda, 0xa8, 0x5b, 0x1b, 0xba, 0xc9,
	0xdf, 0xc4, 0xbf, 0x17, 0x6c, 0x9e, 0x8a, 0x56, 0x25, 0x87, 0x8b, 0xa1, 0x77, 0x87, 0x6b, 0x17,
	0x59, 0x0d, 0x21, 0x4c, 0x84, 0x1f, 0xe1, 0x6a, 0x61, 0xc1, 0xdf, 0xfb, 0xa1, 0xf4, 0xcd, 0x5b,
	0xd0, 0x24, 0x45, 0x32, 0x52, 0x26, 0x23, 0x67, 0x59, 0xb2, 0xce, 0xc1, 0xe3, 0xfb, 0xc7, 0x13,
	0xda, 0xef, 0x04, 0xd4, 0xdd, 0xd1, 0xbc, 0x64, 0x9a, 0x95, 0x4c, 0x17, 0x39, 0xc5, 0x89, 0x77,
	0x14, 0xfc, 0x7a, 0xbe, 0x7e, 0x40, 0xfd, 0x7b, 0xbc, 0xc1, 0x21, 0x5e, 0x57, 0xea, 0x37, 0x56,
	0x86, 0x06, 0x19, 0xf9, 0xb9, 0x37, 0xf0, 0xae, 0x0e, 0x23, 0x69, 0x67, 0xe9, 0x98, 0x70, 0x88,
	0xe9, 0xea, 0x4f, 0xca, 0x52, 0x23, 0x28, 0xd5, 0x3e, 0x3d, 0xef, 0x05, 0x55, 0xc2, 0x41, 0xff,
	0x15, 0xfd, 0x09, 0x0b, 0xe8, 0x0d, 0x6d, 0x9d, 0x16, 0x07, 0xa3, 0x9c, 0x6e, 0xe4, 0xf0, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x13, 0xfb, 0x5c, 0xff, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InnerCodeClient is the client API for InnerCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnerCodeClient interface {
	// Check the verification code.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type innerCodeClient struct {
	cc *grpc.ClientConn
}

func NewInnerCodeClient(cc *grpc.ClientConn) InnerCodeClient {
	return &innerCodeClient{cc}
}

func (c *innerCodeClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appootb.captcha.InnerCode/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerCodeServer is the server API for InnerCode service.
type InnerCodeServer interface {
	// Check the verification code.
	Verify(context.Context, *VerifyRequest) (*empty.Empty, error)
}

// UnimplementedInnerCodeServer can be embedded to have forward compatible implementations.
type UnimplementedInnerCodeServer struct {
}

func (*UnimplementedInnerCodeServer) Verify(ctx context.Context, req *VerifyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterInnerCodeServer(s *grpc.Server, srv InnerCodeServer) {
	s.RegisterService(&_InnerCode_serviceDesc, srv)
}

func _InnerCode_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerCodeServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.captcha.InnerCode/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerCodeServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerCode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.captcha.InnerCode",
	HandlerType: (*InnerCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _InnerCode_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_code.proto",
}
