// Code generated by protoc-gen-auth. DO NOT EDIT!
// source: inner_filter.proto
package strainer

import (
	"github.com/appootb/protobuf/go/permission"
	"github.com/appootb/protobuf/go/service"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = permission.TokenLevel_NONE_TOKEN
var _ = service.UnaryServerInterceptor

var _levelInnerFilter = map[string]permission.TokenLevel{
	"/appootb.strainer.InnerFilter/Filter": permission.TokenLevel_INNER_TOKEN,
}

// Register scoped server.
func RegisterInnerFilterScopeServer(auth service.Authenticator, impl service.Implementor, srv InnerFilterServer) error {
	// Register service required token level.
	auth.RegisterServiceTokenLevel(_levelInnerFilter)

	// Register scoped gRPC server.
	for _, grpc := range impl.GetScopedGRPCServer(permission.VisibleScope_INNER_SCOPE) {
		RegisterInnerFilterServer(grpc, srv)
	}
	// Register scoped gateway handler.
	return impl.RegisterGateway(permission.VisibleScope_INNER_SCOPE, RegisterInnerFilterHandler)
}
