// Code generated by protoc-gen-go. DO NOT EDIT.
// source: include.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message category enums.
type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_CATEGORY_PRIVATE     Category = 1
	Category_CATEGORY_GROUP       Category = 2
	Category_CATEGORY_CHANNEL     Category = 3
	Category_CATEGORY_ROOM        Category = 4
)

var Category_name = map[int32]string{
	0: "CATEGORY_UNSPECIFIED",
	1: "CATEGORY_PRIVATE",
	2: "CATEGORY_GROUP",
	3: "CATEGORY_CHANNEL",
	4: "CATEGORY_ROOM",
}

var Category_value = map[string]int32{
	"CATEGORY_UNSPECIFIED": 0,
	"CATEGORY_PRIVATE":     1,
	"CATEGORY_GROUP":       2,
	"CATEGORY_CHANNEL":     3,
	"CATEGORY_ROOM":        4,
}

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return proto.EnumName(Category_name, int32(x))
}

func (x *Category) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Category_value, data, "Category")
	if err != nil {
		return err
	}
	*x = Category(value)
	return nil
}

func (Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{0}
}

// Message type enums.
type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_TYPE_TEXT        Type = 1
	Type_TYPE_AUDIO       Type = 2
	Type_TYPE_STICKER     Type = 3
	Type_TYPE_PHOTO       Type = 4
	Type_TYPE_VIDEO       Type = 5
	Type_TYPE_GIF         Type = 6
	Type_TYPE_FILE        Type = 7
	Type_TYPE_LOCATION    Type = 8
	Type_TYPE_CONTACT     Type = 9
	Type_TYPE_RECALL      Type = 10
	Type_TYPE_READ        Type = 11
)

var Type_name = map[int32]string{
	0:  "TYPE_UNSPECIFIED",
	1:  "TYPE_TEXT",
	2:  "TYPE_AUDIO",
	3:  "TYPE_STICKER",
	4:  "TYPE_PHOTO",
	5:  "TYPE_VIDEO",
	6:  "TYPE_GIF",
	7:  "TYPE_FILE",
	8:  "TYPE_LOCATION",
	9:  "TYPE_CONTACT",
	10: "TYPE_RECALL",
	11: "TYPE_READ",
}

var Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"TYPE_TEXT":        1,
	"TYPE_AUDIO":       2,
	"TYPE_STICKER":     3,
	"TYPE_PHOTO":       4,
	"TYPE_VIDEO":       5,
	"TYPE_GIF":         6,
	"TYPE_FILE":        7,
	"TYPE_LOCATION":    8,
	"TYPE_CONTACT":     9,
	"TYPE_RECALL":      10,
	"TYPE_READ":        11,
}

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (x *Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_value, data, "Type")
	if err != nil {
		return err
	}
	*x = Type(value)
	return nil
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{1}
}

// Message stream payload type.
type PayloadType int32

const (
	PayloadType_PAYLOAD_TYPE_UNSPECIFIED PayloadType = 0
	PayloadType_PAYLOAD_TYPE_PING        PayloadType = 1
	PayloadType_PAYLOAD_TYPE_PONG        PayloadType = 2
	PayloadType_PAYLOAD_TYPE_SYNC        PayloadType = 3
	PayloadType_PAYLOAD_TYPE_MESSAGES    PayloadType = 4
	PayloadType_PAYLOAD_TYPE_RECEIPTS    PayloadType = 5
)

var PayloadType_name = map[int32]string{
	0: "PAYLOAD_TYPE_UNSPECIFIED",
	1: "PAYLOAD_TYPE_PING",
	2: "PAYLOAD_TYPE_PONG",
	3: "PAYLOAD_TYPE_SYNC",
	4: "PAYLOAD_TYPE_MESSAGES",
	5: "PAYLOAD_TYPE_RECEIPTS",
}

var PayloadType_value = map[string]int32{
	"PAYLOAD_TYPE_UNSPECIFIED": 0,
	"PAYLOAD_TYPE_PING":        1,
	"PAYLOAD_TYPE_PONG":        2,
	"PAYLOAD_TYPE_SYNC":        3,
	"PAYLOAD_TYPE_MESSAGES":    4,
	"PAYLOAD_TYPE_RECEIPTS":    5,
}

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return proto.EnumName(PayloadType_name, int32(x))
}

func (x *PayloadType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PayloadType_value, data, "PayloadType")
	if err != nil {
		return err
	}
	*x = PayloadType(value)
	return nil
}

func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{2}
}

// Message postmark.
type Postmark struct {
	Category             *Category            `protobuf:"varint,1,req,name=category,enum=appootb.message.Category" json:"category,omitempty"`
	Sender               *uint64              `protobuf:"varint,2,req,name=sender" json:"sender,omitempty"`
	Receiver             *uint64              `protobuf:"varint,3,req,name=receiver" json:"receiver,omitempty"`
	UniqueId             *uint64              `protobuf:"varint,4,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	Expire               *duration.Duration   `protobuf:"bytes,8,opt,name=expire" json:"expire,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Postmark) Reset()         { *m = Postmark{} }
func (m *Postmark) String() string { return proto.CompactTextString(m) }
func (*Postmark) ProtoMessage()    {}
func (*Postmark) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{0}
}

func (m *Postmark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Postmark.Unmarshal(m, b)
}
func (m *Postmark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Postmark.Marshal(b, m, deterministic)
}
func (m *Postmark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Postmark.Merge(m, src)
}
func (m *Postmark) XXX_Size() int {
	return xxx_messageInfo_Postmark.Size(m)
}
func (m *Postmark) XXX_DiscardUnknown() {
	xxx_messageInfo_Postmark.DiscardUnknown(m)
}

var xxx_messageInfo_Postmark proto.InternalMessageInfo

func (m *Postmark) GetCategory() Category {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (m *Postmark) GetSender() uint64 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *Postmark) GetReceiver() uint64 {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return 0
}

func (m *Postmark) GetUniqueId() uint64 {
	if m != nil && m.UniqueId != nil {
		return *m.UniqueId
	}
	return 0
}

func (m *Postmark) GetExpire() *duration.Duration {
	if m != nil {
		return m.Expire
	}
	return nil
}

func (m *Postmark) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// Text message.
type Text struct {
	Content              *string  `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{1}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

// Media message.
type Media struct {
	Url                  *string  `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Thumbnail            *string  `protobuf:"bytes,2,opt,name=thumbnail" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{2}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Media) GetThumbnail() string {
	if m != nil && m.Thumbnail != nil {
		return *m.Thumbnail
	}
	return ""
}

// Location coordinate.
type Location struct {
	Latitude             *float32 `protobuf:"fixed32,1,req,name=latitude" json:"latitude,omitempty"`
	Longitude            *float32 `protobuf:"fixed32,2,req,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

// Message post.
type Post struct {
	Postmark *Postmark `protobuf:"bytes,1,req,name=postmark" json:"postmark,omitempty"`
	Type     *Type     `protobuf:"varint,2,req,name=type,enum=appootb.message.Type" json:"type,omitempty"`
	// Message content
	//
	// Types that are valid to be assigned to Envelope:
	//	*Post_Text
	//	*Post_Resource
	//	*Post_Coordinate
	Envelope             isPost_Envelope `protobuf_oneof:"envelope"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{4}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPostmark() *Postmark {
	if m != nil {
		return m.Postmark
	}
	return nil
}

func (m *Post) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

type isPost_Envelope interface {
	isPost_Envelope()
}

type Post_Text struct {
	Text *Text `protobuf:"bytes,10,opt,name=text,oneof"`
}

type Post_Resource struct {
	Resource *Media `protobuf:"bytes,11,opt,name=resource,oneof"`
}

type Post_Coordinate struct {
	Coordinate *Location `protobuf:"bytes,12,opt,name=coordinate,oneof"`
}

func (*Post_Text) isPost_Envelope() {}

func (*Post_Resource) isPost_Envelope() {}

func (*Post_Coordinate) isPost_Envelope() {}

func (m *Post) GetEnvelope() isPost_Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func (m *Post) GetText() *Text {
	if x, ok := m.GetEnvelope().(*Post_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Post) GetResource() *Media {
	if x, ok := m.GetEnvelope().(*Post_Resource); ok {
		return x.Resource
	}
	return nil
}

func (m *Post) GetCoordinate() *Location {
	if x, ok := m.GetEnvelope().(*Post_Coordinate); ok {
		return x.Coordinate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Post) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Post_Text)(nil),
		(*Post_Resource)(nil),
		(*Post_Coordinate)(nil),
	}
}

// Message postbox.
type Postbox struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Postbox) Reset()         { *m = Postbox{} }
func (m *Postbox) String() string { return proto.CompactTextString(m) }
func (*Postbox) ProtoMessage()    {}
func (*Postbox) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{5}
}

func (m *Postbox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Postbox.Unmarshal(m, b)
}
func (m *Postbox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Postbox.Marshal(b, m, deterministic)
}
func (m *Postbox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Postbox.Merge(m, src)
}
func (m *Postbox) XXX_Size() int {
	return xxx_messageInfo_Postbox.Size(m)
}
func (m *Postbox) XXX_DiscardUnknown() {
	xxx_messageInfo_Postbox.DiscardUnknown(m)
}

var xxx_messageInfo_Postbox proto.InternalMessageInfo

func (m *Postbox) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

// Message receipts.
type Receipts struct {
	LocalIds             []*ClientId `protobuf:"bytes,1,rep,name=local_ids,json=localIds" json:"local_ids,omitempty"`
	Postmarks            []*Postmark `protobuf:"bytes,2,rep,name=postmarks" json:"postmarks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Receipts) Reset()         { *m = Receipts{} }
func (m *Receipts) String() string { return proto.CompactTextString(m) }
func (*Receipts) ProtoMessage()    {}
func (*Receipts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{6}
}

func (m *Receipts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipts.Unmarshal(m, b)
}
func (m *Receipts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipts.Marshal(b, m, deterministic)
}
func (m *Receipts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipts.Merge(m, src)
}
func (m *Receipts) XXX_Size() int {
	return xxx_messageInfo_Receipts.Size(m)
}
func (m *Receipts) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipts.DiscardUnknown(m)
}

var xxx_messageInfo_Receipts proto.InternalMessageInfo

func (m *Receipts) GetLocalIds() []*ClientId {
	if m != nil {
		return m.LocalIds
	}
	return nil
}

func (m *Receipts) GetPostmarks() []*Postmark {
	if m != nil {
		return m.Postmarks
	}
	return nil
}

// Client local ID.
type ClientId struct {
	Category             *Category `protobuf:"varint,1,req,name=category,enum=appootb.message.Category" json:"category,omitempty"`
	LastId               *uint64   `protobuf:"varint,2,opt,name=last_id,json=lastId" json:"last_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ClientId) Reset()         { *m = ClientId{} }
func (m *ClientId) String() string { return proto.CompactTextString(m) }
func (*ClientId) ProtoMessage()    {}
func (*ClientId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{7}
}

func (m *ClientId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientId.Unmarshal(m, b)
}
func (m *ClientId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientId.Marshal(b, m, deterministic)
}
func (m *ClientId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientId.Merge(m, src)
}
func (m *ClientId) XXX_Size() int {
	return xxx_messageInfo_ClientId.Size(m)
}
func (m *ClientId) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientId.DiscardUnknown(m)
}

var xxx_messageInfo_ClientId proto.InternalMessageInfo

func (m *ClientId) GetCategory() Category {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (m *ClientId) GetLastId() uint64 {
	if m != nil && m.LastId != nil {
		return *m.LastId
	}
	return 0
}

// Client local IDs.
type ClientIds struct {
	Ids                  []*ClientId `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientIds) Reset()         { *m = ClientIds{} }
func (m *ClientIds) String() string { return proto.CompactTextString(m) }
func (*ClientIds) ProtoMessage()    {}
func (*ClientIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{8}
}

func (m *ClientIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIds.Unmarshal(m, b)
}
func (m *ClientIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIds.Marshal(b, m, deterministic)
}
func (m *ClientIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIds.Merge(m, src)
}
func (m *ClientIds) XXX_Size() int {
	return xxx_messageInfo_ClientIds.Size(m)
}
func (m *ClientIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIds.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIds proto.InternalMessageInfo

func (m *ClientIds) GetIds() []*ClientId {
	if m != nil {
		return m.Ids
	}
	return nil
}

// Message streaming.
type Stream struct {
	Sn     *string      `protobuf:"bytes,1,req,name=sn" json:"sn,omitempty"`
	Target *uint64      `protobuf:"varint,2,opt,name=target" json:"target,omitempty"`
	Type   *PayloadType `protobuf:"varint,3,req,name=type,enum=appootb.message.PayloadType" json:"type,omitempty"`
	// Payload data
	//
	// Types that are valid to be assigned to Payload:
	//	*Stream_Local
	//	*Stream_Postbox
	//	*Stream_Receipts
	Payload              isStream_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{9}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetSn() string {
	if m != nil && m.Sn != nil {
		return *m.Sn
	}
	return ""
}

func (m *Stream) GetTarget() uint64 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func (m *Stream) GetType() PayloadType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PayloadType_PAYLOAD_TYPE_UNSPECIFIED
}

type isStream_Payload interface {
	isStream_Payload()
}

type Stream_Local struct {
	Local *ClientIds `protobuf:"bytes,10,opt,name=local,oneof"`
}

type Stream_Postbox struct {
	Postbox *Postbox `protobuf:"bytes,11,opt,name=postbox,oneof"`
}

type Stream_Receipts struct {
	Receipts *Receipts `protobuf:"bytes,12,opt,name=receipts,oneof"`
}

func (*Stream_Local) isStream_Payload() {}

func (*Stream_Postbox) isStream_Payload() {}

func (*Stream_Receipts) isStream_Payload() {}

func (m *Stream) GetPayload() isStream_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Stream) GetLocal() *ClientIds {
	if x, ok := m.GetPayload().(*Stream_Local); ok {
		return x.Local
	}
	return nil
}

func (m *Stream) GetPostbox() *Postbox {
	if x, ok := m.GetPayload().(*Stream_Postbox); ok {
		return x.Postbox
	}
	return nil
}

func (m *Stream) GetReceipts() *Receipts {
	if x, ok := m.GetPayload().(*Stream_Receipts); ok {
		return x.Receipts
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Stream) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Stream_Local)(nil),
		(*Stream_Postbox)(nil),
		(*Stream_Receipts)(nil),
	}
}

// Connections.
type Connections struct {
	Product              *string  `protobuf:"bytes,1,req,name=product" json:"product,omitempty"`
	UniqueIds            []string `protobuf:"bytes,2,rep,name=unique_ids,json=uniqueIds" json:"unique_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connections) Reset()         { *m = Connections{} }
func (m *Connections) String() string { return proto.CompactTextString(m) }
func (*Connections) ProtoMessage()    {}
func (*Connections) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{10}
}

func (m *Connections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connections.Unmarshal(m, b)
}
func (m *Connections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connections.Marshal(b, m, deterministic)
}
func (m *Connections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connections.Merge(m, src)
}
func (m *Connections) XXX_Size() int {
	return xxx_messageInfo_Connections.Size(m)
}
func (m *Connections) XXX_DiscardUnknown() {
	xxx_messageInfo_Connections.DiscardUnknown(m)
}

var xxx_messageInfo_Connections proto.InternalMessageInfo

func (m *Connections) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *Connections) GetUniqueIds() []string {
	if m != nil {
		return m.UniqueIds
	}
	return nil
}

// Connection tags.
type Tag struct {
	Product              *string  `protobuf:"bytes,1,req,name=product" json:"product,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Prefixed             *bool    `protobuf:"varint,3,opt,name=prefixed" json:"prefixed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{11}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Tag) GetPrefixed() bool {
	if m != nil && m.Prefixed != nil {
		return *m.Prefixed
	}
	return false
}

// Router package.
type Package struct {
	// Target
	//
	// Types that are valid to be assigned to Target:
	//	*Package_Tag
	//	*Package_Conn
	Target               isPackage_Target `protobuf_oneof:"target"`
	Sn                   *string          `protobuf:"bytes,8,req,name=sn" json:"sn,omitempty"`
	Posts                []*Post          `protobuf:"bytes,9,rep,name=posts" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{12}
}

func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

type isPackage_Target interface {
	isPackage_Target()
}

type Package_Tag struct {
	Tag *Tag `protobuf:"bytes,1,opt,name=tag,oneof"`
}

type Package_Conn struct {
	Conn *Connections `protobuf:"bytes,2,opt,name=conn,oneof"`
}

func (*Package_Tag) isPackage_Target() {}

func (*Package_Conn) isPackage_Target() {}

func (m *Package) GetTarget() isPackage_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Package) GetTag() *Tag {
	if x, ok := m.GetTarget().(*Package_Tag); ok {
		return x.Tag
	}
	return nil
}

func (m *Package) GetConn() *Connections {
	if x, ok := m.GetTarget().(*Package_Conn); ok {
		return x.Conn
	}
	return nil
}

func (m *Package) GetSn() string {
	if m != nil && m.Sn != nil {
		return *m.Sn
	}
	return ""
}

func (m *Package) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Package) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Package_Tag)(nil),
		(*Package_Conn)(nil),
	}
}

func init() {
	proto.RegisterEnum("appootb.message.Category", Category_name, Category_value)
	proto.RegisterEnum("appootb.message.Type", Type_name, Type_value)
	proto.RegisterEnum("appootb.message.PayloadType", PayloadType_name, PayloadType_value)
	proto.RegisterType((*Postmark)(nil), "appootb.message.Postmark")
	proto.RegisterType((*Text)(nil), "appootb.message.Text")
	proto.RegisterType((*Media)(nil), "appootb.message.Media")
	proto.RegisterType((*Location)(nil), "appootb.message.Location")
	proto.RegisterType((*Post)(nil), "appootb.message.Post")
	proto.RegisterType((*Postbox)(nil), "appootb.message.Postbox")
	proto.RegisterType((*Receipts)(nil), "appootb.message.Receipts")
	proto.RegisterType((*ClientId)(nil), "appootb.message.ClientId")
	proto.RegisterType((*ClientIds)(nil), "appootb.message.ClientIds")
	proto.RegisterType((*Stream)(nil), "appootb.message.Stream")
	proto.RegisterType((*Connections)(nil), "appootb.message.Connections")
	proto.RegisterType((*Tag)(nil), "appootb.message.Tag")
	proto.RegisterType((*Package)(nil), "appootb.message.Package")
}

func init() { proto.RegisterFile("include.proto", fileDescriptor_f1eef7b97e24a48e) }

var fileDescriptor_f1eef7b97e24a48e = []byte{
	// 1119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x29, 0xd9, 0x22, 0x47, 0x89, 0xb3, 0xd9, 0xc6, 0x29, 0xe3, 0xa6, 0xad, 0xc0, 0x43,
	0xe1, 0x26, 0x80, 0xdc, 0x1a, 0x69, 0x12, 0xa0, 0x27, 0x99, 0xa2, 0x2d, 0xa2, 0xb2, 0x48, 0xac,
	0x98, 0xa0, 0x0e, 0x02, 0x18, 0x14, 0xb9, 0x51, 0x88, 0x48, 0x5c, 0x96, 0x5c, 0xa5, 0x32, 0xfa,
	0x12, 0x3d, 0xf4, 0x09, 0x7a, 0xe8, 0xa1, 0x87, 0x3e, 0x48, 0x2f, 0x7d, 0x9d, 0xde, 0x5a, 0xec,
	0xf2, 0xc7, 0x8e, 0xa5, 0xb4, 0x45, 0x6f, 0x9c, 0x99, 0xef, 0x9b, 0xdd, 0x99, 0xf9, 0x66, 0x25,
	0xb8, 0x19, 0x27, 0xe1, 0x7c, 0x19, 0xd1, 0x5e, 0x9a, 0x31, 0xce, 0xf0, 0xad, 0x20, 0x4d, 0x19,
	0xe3, 0xd3, 0xde, 0x82, 0xe6, 0x79, 0x30, 0xa3, 0x7b, 0x9f, 0xcc, 0x18, 0x9b, 0xcd, 0xe9, 0x81,
	0x0c, 0x4f, 0x97, 0xaf, 0x0e, 0xa2, 0x65, 0x16, 0xf0, 0x98, 0x25, 0x05, 0x61, 0xef, 0xd3, 0xeb,
	0x71, 0x1e, 0x2f, 0x68, 0xce, 0x83, 0x45, 0x5a, 0x00, 0xcc, 0xbf, 0x14, 0xd0, 0x3c, 0x96, 0xf3,
	0x45, 0x90, 0xbd, 0xc1, 0x5f, 0x81, 0x16, 0x06, 0x9c, 0xce, 0x58, 0x76, 0x61, 0x28, 0x5d, 0x75,
	0x7f, 0xe7, 0xf0, 0x5e, 0xef, 0xda, 0x89, 0x3d, 0xab, 0x04, 0x90, 0x1a, 0x8a, 0xef, 0xc2, 0x76,
	0x4e, 0x93, 0x88, 0x66, 0x86, 0xda, 0x55, 0xf7, 0x5b, 0xa4, 0xb4, 0xf0, 0x1e, 0x68, 0x19, 0x0d,
	0x69, 0xfc, 0x96, 0x66, 0x46, 0x53, 0x46, 0x6a, 0x1b, 0x7f, 0x04, 0xfa, 0x32, 0x89, 0xbf, 0x5b,
	0xd2, 0xf3, 0x38, 0x32, 0x5a, 0x5d, 0x45, 0x04, 0x0b, 0x87, 0x13, 0xe1, 0x2f, 0x61, 0x9b, 0xae,
	0xd2, 0x38, 0xa3, 0x86, 0xd6, 0x55, 0xf6, 0x3b, 0x87, 0xf7, 0x7a, 0x45, 0x19, 0xbd, 0xaa, 0x8c,
	0xde, 0xa0, 0x2c, 0x93, 0x94, 0x40, 0xfc, 0x14, 0xf4, 0xba, 0x34, 0x43, 0x97, 0xac, 0xbd, 0x35,
	0x96, 0x5f, 0x21, 0xc8, 0x25, 0xd8, 0xec, 0x42, 0xcb, 0xa7, 0x2b, 0x8e, 0x0d, 0x68, 0x87, 0x2c,
	0xe1, 0x34, 0xe1, 0xb2, 0x76, 0x9d, 0x54, 0xa6, 0xf9, 0x04, 0xb6, 0x4e, 0x69, 0x14, 0x07, 0x18,
	0x41, 0x73, 0x99, 0xcd, 0xcb, 0xb0, 0xf8, 0xc4, 0xf7, 0x41, 0xe7, 0xaf, 0x97, 0x8b, 0x69, 0x12,
	0xc4, 0x73, 0x43, 0xed, 0x2a, 0xfb, 0x3a, 0xb9, 0x74, 0x98, 0x03, 0xd0, 0x46, 0x2c, 0x94, 0x17,
	0x15, 0xcd, 0x98, 0x07, 0x3c, 0xe6, 0xcb, 0x88, 0xca, 0x04, 0x2a, 0xa9, 0x6d, 0x91, 0x65, 0xce,
	0x92, 0x59, 0x11, 0x54, 0x65, 0xf0, 0xd2, 0x61, 0xfe, 0xa4, 0x42, 0x4b, 0x8c, 0x48, 0x8c, 0x27,
	0x2d, 0x47, 0x25, 0x53, 0x74, 0x36, 0x8c, 0xa7, 0x9a, 0x25, 0xa9, 0xa1, 0xf8, 0x73, 0x68, 0xf1,
	0x8b, 0xb4, 0x48, 0xbc, 0x73, 0xb8, 0xbb, 0x46, 0xf1, 0x2f, 0x52, 0x4a, 0x24, 0x04, 0x3f, 0x84,
	0x16, 0xa7, 0x2b, 0x6e, 0x80, 0x6c, 0xe0, 0x06, 0x28, 0x5d, 0xf1, 0x61, 0x83, 0x48, 0x10, 0x7e,
	0x24, 0xc6, 0x9b, 0xb3, 0x65, 0x16, 0x52, 0xa3, 0x23, 0x09, 0x77, 0xd7, 0x08, 0xb2, 0x6f, 0xc3,
	0x06, 0xa9, 0x91, 0xf8, 0x6b, 0x80, 0x90, 0xb1, 0x2c, 0x8a, 0x93, 0x80, 0x53, 0xe3, 0x46, 0x39,
	0xdf, 0xeb, 0xbc, 0xaa, 0x6d, 0xc3, 0x06, 0xb9, 0x02, 0x3f, 0x02, 0xd0, 0x68, 0xf2, 0x96, 0xce,
	0x59, 0x4a, 0xcd, 0xc7, 0xd0, 0x16, 0xc5, 0x4e, 0xd9, 0x0a, 0x3f, 0x84, 0x2d, 0x51, 0x6d, 0x6e,
	0x28, 0xdd, 0xe6, 0xc6, 0x7b, 0x0b, 0x20, 0x29, 0x30, 0xe6, 0x0f, 0xa0, 0x11, 0xa1, 0xc2, 0x94,
	0xe7, 0xf8, 0xb1, 0x68, 0x7c, 0x18, 0xcc, 0xcf, 0xe3, 0xa8, 0x22, 0x6f, 0x50, 0xfc, 0x3c, 0xa6,
	0x09, 0x77, 0x22, 0xa2, 0x49, 0xac, 0x13, 0xe5, 0xf8, 0x09, 0xe8, 0x55, 0x7b, 0x73, 0x43, 0x7d,
	0x0f, 0xaf, 0x1e, 0xc5, 0x25, 0xd6, 0x7c, 0x01, 0x5a, 0x95, 0xee, 0xff, 0x6e, 0xdb, 0x87, 0xd0,
	0x9e, 0x07, 0x39, 0x17, 0x7b, 0xa3, 0xca, 0xbd, 0xd9, 0x16, 0xa6, 0x13, 0x99, 0x4f, 0x41, 0xaf,
	0x72, 0xe7, 0xf8, 0x21, 0x34, 0xff, 0x53, 0x4d, 0x02, 0x65, 0xfe, 0xa8, 0xc2, 0xf6, 0x84, 0x67,
	0x34, 0x58, 0xe0, 0x1d, 0x50, 0xf3, 0xa4, 0x54, 0xb8, 0x9a, 0x27, 0x62, 0xb7, 0x79, 0x90, 0xcd,
	0x28, 0xaf, 0x0e, 0x2b, 0x2c, 0xfc, 0x45, 0x29, 0xaa, 0xa6, 0xbc, 0xf8, 0xfd, 0xf5, 0xe2, 0x83,
	0x8b, 0x39, 0x0b, 0xa2, 0x2b, 0xda, 0x3a, 0x84, 0x2d, 0xd9, 0xbf, 0x52, 0x5c, 0x7b, 0xef, 0xbd,
	0x53, 0x3e, 0x6c, 0x90, 0x02, 0x8a, 0x1f, 0x41, 0x3b, 0x2d, 0x66, 0x5c, 0x2a, 0xcc, 0xd8, 0xd8,
	0xe5, 0x29, 0x5b, 0x0d, 0x1b, 0xa4, 0x82, 0xe2, 0x27, 0xe5, 0xbb, 0x93, 0xf2, 0xfc, 0xbd, 0x02,
	0xab, 0x24, 0x50, 0x68, 0xb3, 0xf8, 0x3e, 0xd2, 0xa1, 0x9d, 0x16, 0xf7, 0x36, 0x8f, 0xa1, 0x63,
	0xb1, 0x24, 0xa1, 0xa1, 0x50, 0x61, 0x2e, 0x1e, 0x87, 0x34, 0x63, 0xd1, 0x32, 0xac, 0x1f, 0x87,
	0xd2, 0xc4, 0x1f, 0x03, 0xd4, 0x0f, 0x59, 0xa1, 0x05, 0x9d, 0xe8, 0xd5, 0x4b, 0x96, 0x9b, 0x2e,
	0x34, 0xfd, 0x60, 0xf6, 0x0f, 0x7c, 0x0c, 0xad, 0x24, 0x58, 0x14, 0xdb, 0xa9, 0x13, 0xf9, 0x2d,
	0xde, 0x8a, 0x34, 0xa3, 0xaf, 0xe2, 0x15, 0x8d, 0x8c, 0x66, 0x57, 0xd9, 0xd7, 0x48, 0x6d, 0x9b,
	0xbf, 0x29, 0xd0, 0xf6, 0x82, 0xf0, 0x4d, 0x30, 0xa3, 0x78, 0x1f, 0x9a, 0x3c, 0x98, 0x19, 0x8a,
	0xac, 0xf1, 0xce, 0xfa, 0xb6, 0x06, 0xb3, 0x61, 0x83, 0x08, 0x08, 0x3e, 0x84, 0x56, 0xc8, 0x92,
	0x44, 0x0e, 0xb1, 0xb3, 0x61, 0x5c, 0x57, 0x6a, 0x15, 0xfb, 0x2d, 0xb0, 0xa5, 0x14, 0xb4, 0x5a,
	0x0a, 0xf5, 0x96, 0xe9, 0xff, 0xbe, 0x65, 0x47, 0x5a, 0xa5, 0x9b, 0x07, 0xdf, 0x83, 0x56, 0xa9,
	0x18, 0x1b, 0x70, 0xc7, 0xea, 0xfb, 0xf6, 0x89, 0x4b, 0xce, 0xce, 0x9f, 0x8d, 0x27, 0x9e, 0x6d,
	0x39, 0xc7, 0x8e, 0x3d, 0x40, 0x0d, 0x7c, 0x07, 0x50, 0x1d, 0xf1, 0x88, 0xf3, 0xbc, 0xef, 0xdb,
	0x48, 0xc1, 0x18, 0x76, 0x6a, 0xef, 0x09, 0x71, 0x9f, 0x79, 0x48, 0x7d, 0x07, 0x69, 0x0d, 0xfb,
	0xe3, 0xb1, 0x3d, 0x42, 0x4d, 0x7c, 0x1b, 0x6e, 0xd6, 0x5e, 0xe2, 0xba, 0xa7, 0xa8, 0xf5, 0xe0,
	0x0f, 0x05, 0x5a, 0x42, 0x7f, 0x82, 0xe1, 0x9f, 0x79, 0xf6, 0xb5, 0x13, 0x6f, 0x82, 0x2e, 0xbd,
	0xbe, 0xfd, 0xad, 0x8f, 0x14, 0xbc, 0x03, 0x20, 0xcd, 0xfe, 0xb3, 0x81, 0xe3, 0x22, 0x15, 0x23,
	0xb8, 0x21, 0xed, 0x89, 0xef, 0x58, 0xdf, 0xd8, 0x04, 0x35, 0x6b, 0x84, 0x37, 0x74, 0x7d, 0x17,
	0xb5, 0x6a, 0xfb, 0xb9, 0x33, 0xb0, 0x5d, 0xb4, 0x85, 0x6f, 0x80, 0x26, 0xed, 0x13, 0xe7, 0x18,
	0x6d, 0xd7, 0xe9, 0x8f, 0x9d, 0x91, 0x8d, 0xda, 0xe2, 0x7e, 0xd2, 0x1c, 0xb9, 0x56, 0xdf, 0x77,
	0xdc, 0x31, 0xd2, 0xea, 0x13, 0x2c, 0x77, 0xec, 0xf7, 0x2d, 0x1f, 0xe9, 0xf8, 0x16, 0x74, 0xa4,
	0x87, 0xd8, 0x56, 0x7f, 0x34, 0x42, 0x50, 0x27, 0x21, 0x76, 0x7f, 0x80, 0x3a, 0x0f, 0x7e, 0x51,
	0xa0, 0x73, 0x65, 0xb1, 0xf0, 0x7d, 0x30, 0xbc, 0xfe, 0xd9, 0xc8, 0xed, 0x0f, 0xce, 0x37, 0x14,
	0xb8, 0x0b, 0xb7, 0xdf, 0x89, 0x7a, 0xce, 0xf8, 0x04, 0x29, 0xeb, 0x6e, 0x77, 0x7c, 0x82, 0xd4,
	0x35, 0xf7, 0xe4, 0x6c, 0x6c, 0xa1, 0x26, 0xbe, 0x07, 0xbb, 0xef, 0xb8, 0x4f, 0xed, 0xc9, 0xa4,
	0x7f, 0x62, 0x4f, 0x50, 0x6b, 0x2d, 0x44, 0x6c, 0xcb, 0x76, 0x3c, 0x7f, 0x82, 0xb6, 0x8e, 0x2e,
	0xe0, 0x83, 0x90, 0x2d, 0xae, 0x0b, 0xe4, 0xa8, 0x63, 0xb1, 0xc5, 0x82, 0x25, 0x9e, 0xf8, 0x3d,
	0x1e, 0x2a, 0x9e, 0xf2, 0xe2, 0xb3, 0x59, 0xcc, 0x5f, 0x2f, 0xa7, 0xbd, 0x90, 0x2d, 0x0e, 0x4a,
	0xf0, 0xe5, 0x5f, 0x95, 0x19, 0x3b, 0x28, 0x89, 0x7f, 0x2a, 0xca, 0xcf, 0x6a, 0xd3, 0xf2, 0x8e,
	0x7e, 0x55, 0xdb, 0xa7, 0x85, 0xeb, 0x77, 0x75, 0xb7, 0x5f, 0x10, 0x5e, 0xca, 0x74, 0x2f, 0x4b,
	0xff, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x94, 0xf0, 0x20, 0x32, 0x09, 0x00, 0x00,
}
