// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_chat.proto

package message

import (
	context "context"
	fmt "fmt"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("inner_chat.proto", fileDescriptor_0c95ff7eff2c16d4) }

var fileDescriptor_0c95ff7eff2c16d4 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4a, 0x03, 0x41,
	0x10, 0x87, 0xb9, 0x33, 0x10, 0x3c, 0xf0, 0x0f, 0x27, 0x8a, 0x24, 0x29, 0x42, 0x8a, 0x14, 0x29,
	0x76, 0xd0, 0x46, 0xb0, 0x33, 0x51, 0x50, 0x44, 0xb8, 0x5a, 0x82, 0x61, 0xb3, 0xb7, 0x5e, 0x96,
	0xe4, 0x76, 0xd6, 0xdb, 0xdd, 0x80, 0xc4, 0x80, 0xf8, 0x0a, 0x36, 0xd6, 0x96, 0x3e, 0x8a, 0xad,
	0xaf, 0x60, 0x6b, 0x6f, 0x29, 0x77, 0xb7, 0x49, 0x11, 0xb5, 0xdc, 0x19, 0xe6, 0xfb, 0xe6, 0x37,
	0x1b, 0x6c, 0x0b, 0x29, 0x79, 0x36, 0x60, 0x23, 0x6a, 0x88, 0xca, 0xd0, 0x60, 0xb8, 0x45, 0x95,
	0x42, 0x34, 0x43, 0x92, 0x72, 0xad, 0x69, 0xc2, 0x6b, 0x4d, 0x57, 0x00, 0xc5, 0xb3, 0x54, 0x68,
	0x2d, 0x50, 0x82, 0xe6, 0xd9, 0x54, 0x30, 0x5e, 0x8e, 0xd4, 0x1a, 0x09, 0x62, 0x32, 0xe1, 0x40,
	0x95, 0x00, 0x2a, 0x25, 0x1a, 0x6a, 0x04, 0x4a, 0xed, 0xba, 0x75, 0xd7, 0x2d, 0x5e, 0x43, 0x7b,
	0x0b, 0x3c, 0x55, 0xe6, 0xde, 0x35, 0x37, 0x84, 0x64, 0x13, 0x1b, 0x3b, 0xd2, 0xe1, 0x97, 0x17,
	0xac, 0x5f, 0xe4, 0x1b, 0xf5, 0x46, 0xd4, 0x84, 0x2c, 0xa8, 0x9e, 0xf2, 0x89, 0x98, 0xf2, 0x2c,
	0xdc, 0x27, 0x2b, 0x6b, 0x91, 0x88, 0xb2, 0x71, 0xbe, 0xde, 0x1e, 0x29, 0xf9, 0x64, 0xc1, 0x27,
	0x67, 0x39, 0xbf, 0xd5, 0x7e, 0xfa, 0xf8, 0x7c, 0xf6, 0x9b, 0xad, 0x3a, 0xb8, 0x09, 0x28, 0xa2,
	0x42, 0x1e, 0x15, 0xe2, 0x12, 0x7b, 0xec, 0x75, 0x42, 0x1b, 0x54, 0x2e, 0x05, 0x1b, 0x87, 0x8d,
	0x5f, 0x86, 0x1e, 0x4a, 0xc9, 0x59, 0x11, 0xe5, 0x5f, 0xcb, 0x51, 0x61, 0x39, 0xe8, 0xc0, 0x5f,
	0x16, 0x86, 0x52, 0xc2, 0x4c, 0x65, 0x18, 0x5b, 0x66, 0xe6, 0x30, 0xb3, 0x52, 0xdc, 0x59, 0x3e,
	0x10, 0xb1, 0x9e, 0xd7, 0x2a, 0x2f, 0x37, 0x8f, 0x7e, 0xf7, 0x21, 0xd8, 0x61, 0x98, 0xae, 0x9a,
	0xbb, 0x9b, 0xcb, 0x1b, 0x44, 0xb9, 0xee, 0xdc, 0x8b, 0xbc, 0xeb, 0x76, 0x22, 0xcc, 0xc8, 0x0e,
	0x09, 0xc3, 0x14, 0x96, 0x3f, 0xb2, 0x38, 0x69, 0x82, 0x0b, 0xff, 0xb7, 0xe7, 0xbd, 0xfa, 0x6b,
	0xbd, 0xa8, 0xfb, 0xe6, 0x57, 0xaf, 0xca, 0xd2, 0xbb, 0xbf, 0x7b, 0x52, 0x0e, 0xf4, 0x0b, 0x5c,
	0xdf, 0xd5, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x6a, 0xbf, 0x2b, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InnerChatClient is the client API for InnerChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnerChatClient interface {
	// Deliver message.
	Deliver(ctx context.Context, in *Package, opts ...grpc.CallOption) (*empty.Empty, error)
	// Kick the connection.
	Kick(ctx context.Context, in *Connections, opts ...grpc.CallOption) (*empty.Empty, error)
}

type innerChatClient struct {
	cc *grpc.ClientConn
}

func NewInnerChatClient(cc *grpc.ClientConn) InnerChatClient {
	return &innerChatClient{cc}
}

func (c *innerChatClient) Deliver(ctx context.Context, in *Package, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appootb.message.InnerChat/Deliver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innerChatClient) Kick(ctx context.Context, in *Connections, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appootb.message.InnerChat/Kick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerChatServer is the server API for InnerChat service.
type InnerChatServer interface {
	// Deliver message.
	Deliver(context.Context, *Package) (*empty.Empty, error)
	// Kick the connection.
	Kick(context.Context, *Connections) (*empty.Empty, error)
}

// UnimplementedInnerChatServer can be embedded to have forward compatible implementations.
type UnimplementedInnerChatServer struct {
}

func (*UnimplementedInnerChatServer) Deliver(ctx context.Context, req *Package) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deliver not implemented")
}
func (*UnimplementedInnerChatServer) Kick(ctx context.Context, req *Connections) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kick not implemented")
}

func RegisterInnerChatServer(s *grpc.Server, srv InnerChatServer) {
	s.RegisterService(&_InnerChat_serviceDesc, srv)
}

func _InnerChat_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Package)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerChatServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.message.InnerChat/Deliver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerChatServer).Deliver(ctx, req.(*Package))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnerChat_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Connections)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerChatServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.message.InnerChat/Kick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerChatServer).Kick(ctx, req.(*Connections))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerChat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.message.InnerChat",
	HandlerType: (*InnerChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _InnerChat_Deliver_Handler,
		},
		{
			MethodName: "Kick",
			Handler:    _InnerChat_Kick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_chat.proto",
}
