// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	common "github.com/appootb/protobuf/go/common"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Update account info request.
type VariableInfo struct {
	Nickname             *string  `protobuf:"bytes,1,opt,name=nickname" json:"nickname,omitempty"`
	Avatar               *string  `protobuf:"bytes,2,opt,name=avatar" json:"avatar,omitempty"`
	Signature            *string  `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	Gender               *Gender  `protobuf:"varint,4,opt,name=gender,enum=appootb.account.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VariableInfo) Reset()         { *m = VariableInfo{} }
func (m *VariableInfo) String() string { return proto.CompactTextString(m) }
func (*VariableInfo) ProtoMessage()    {}
func (*VariableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *VariableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableInfo.Unmarshal(m, b)
}
func (m *VariableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableInfo.Marshal(b, m, deterministic)
}
func (m *VariableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableInfo.Merge(m, src)
}
func (m *VariableInfo) XXX_Size() int {
	return xxx_messageInfo_VariableInfo.Size(m)
}
func (m *VariableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VariableInfo proto.InternalMessageInfo

func (m *VariableInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *VariableInfo) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *VariableInfo) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *VariableInfo) GetGender() Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func init() {
	proto.RegisterType((*VariableInfo)(nil), "appootb.account.VariableInfo")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbf, 0xce, 0x12, 0x41,
	0x14, 0xc5, 0x33, 0x0b, 0xe1, 0xcf, 0x04, 0xd0, 0x8c, 0x82, 0xeb, 0x06, 0x94, 0x50, 0x18, 0x62,
	0xb1, 0x93, 0x50, 0xda, 0x81, 0x05, 0xd2, 0x11, 0x12, 0x28, 0x0c, 0x89, 0x19, 0x76, 0x87, 0x65,
	0x22, 0x3b, 0x77, 0xdd, 0x99, 0xb5, 0xd0, 0xd8, 0xf8, 0x06, 0xc6, 0x52, 0x2b, 0x4b, 0x9f, 0xc4,
	0xd8, 0xda, 0xf8, 0x00, 0x3e, 0x84, 0xa5, 0x61, 0x76, 0x16, 0x3f, 0xe0, 0xa3, 0xbc, 0xe7, 0xcc,
	0xf9, 0xcd, 0xdc, 0xb3, 0x8b, 0x9b, 0x2c, 0x08, 0x20, 0x93, 0xda, 0x4f, 0x52, 0xd0, 0x40, 0xee,
	0xb0, 0x24, 0x01, 0xd0, 0x1b, 0xdf, 0xca, 0xde, 0x23, 0x2b, 0xd0, 0x00, 0xe2, 0x18, 0x24, 0xcd,
	0xa4, 0x78, 0x93, 0xf1, 0x57, 0x22, 0xcc, 0x03, 0xde, 0xe3, 0xc2, 0x4f, 0x78, 0x1a, 0x0b, 0xa5,
	0x04, 0x48, 0x1a, 0x73, 0xbd, 0x83, 0xe2, 0x40, 0x37, 0x02, 0x88, 0xf6, 0x9c, 0xb2, 0x44, 0x50,
	0x26, 0x25, 0x68, 0xa6, 0x05, 0x48, 0x65, 0xdd, 0xa6, 0x90, 0xc1, 0x3e, 0x0b, 0x79, 0x3e, 0x0e,
	0x3e, 0x21, 0xdc, 0x58, 0xb1, 0x54, 0xb0, 0xcd, 0x9e, 0xcf, 0xe4, 0x16, 0x88, 0x87, 0x6b, 0x52,
	0x04, 0xaf, 0x25, 0x8b, 0xb9, 0x8b, 0xfa, 0x68, 0x58, 0x5f, 0x1c, 0x67, 0xd2, 0xc1, 0x15, 0xf6,
	0x96, 0x69, 0x96, 0xba, 0x8e, 0x71, 0xec, 0x44, 0xba, 0xb8, 0xae, 0x44, 0x24, 0x99, 0xce, 0x52,
	0xee, 0x96, 0x8c, 0xf5, 0x5f, 0x20, 0x14, 0x57, 0x22, 0x2e, 0x43, 0x9e, 0xba, 0xe5, 0x3e, 0x1a,
	0xb6, 0x46, 0x0f, 0xfc, 0xb3, 0x95, 0xfd, 0xa9, 0xb1, 0x17, 0xf6, 0xd8, 0xe8, 0x8b, 0x83, 0xab,
	0xe3, 0xdc, 0x22, 0x2b, 0x5c, 0x9d, 0x72, 0x6d, 0x5e, 0xe6, 0x1e, 0x73, 0x79, 0x33, 0xfe, 0xd2,
	0x34, 0x33, 0x0b, 0xbd, 0xf6, 0x05, 0xf1, 0x10, 0x18, 0x78, 0x1f, 0x7f, 0xfd, 0xf9, 0xec, 0xdc,
	0x27, 0x84, 0x5a, 0x99, 0x0a, 0xb9, 0x05, 0xfa, 0x5e, 0x84, 0x1f, 0xc8, 0x12, 0xd7, 0x2c, 0x57,
	0x91, 0x87, 0xd7, 0xc0, 0xca, 0xeb, 0xdc, 0x4a, 0x56, 0x83, 0x8e, 0x41, 0xdf, 0x25, 0xad, 0x13,
	0xb4, 0x22, 0x0c, 0xe3, 0x65, 0x12, 0x32, 0x9d, 0x77, 0xd9, 0xbb, 0x48, 0xdf, 0xac, 0xfa, 0xda,
	0xb3, 0x7b, 0xbf, 0xbf, 0xa2, 0x1f, 0x65, 0x73, 0x01, 0x19, 0x35, 0x4f, 0x2e, 0x78, 0x86, 0x9e,
	0x4e, 0xde, 0xe1, 0x7b, 0x01, 0xc4, 0xe7, 0xd1, 0x49, 0xc3, 0x36, 0x36, 0x3f, 0x7c, 0xd6, 0x17,
	0x68, 0x8e, 0x5e, 0x3e, 0x89, 0x84, 0xde, 0x65, 0x66, 0x29, 0x7a, 0xfc, 0x67, 0x0e, 0xee, 0x26,
	0xdb, 0xd2, 0x08, 0x0a, 0xf0, 0x5f, 0x84, 0xbe, 0x39, 0xa5, 0xe7, 0xf3, 0xc9, 0x77, 0xa7, 0x68,
	0xfd, 0xa7, 0xd3, 0x1e, 0xe7, 0x81, 0xb5, 0xc1, 0xad, 0xad, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x02, 0xb2, 0x55, 0x63, 0xbc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// Get account info.
	GetInfo(ctx context.Context, in *common.UniqueId, opts ...grpc.CallOption) (*Info, error)
	// Get account infos.
	GetInfos(ctx context.Context, in *common.UniqueIds, opts ...grpc.CallOption) (*Infos, error)
	// Update account info.
	UpdateInfo(ctx context.Context, in *VariableInfo, opts ...grpc.CallOption) (*Info, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) GetInfo(ctx context.Context, in *common.UniqueId, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/appootb.account.Account/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetInfos(ctx context.Context, in *common.UniqueIds, opts ...grpc.CallOption) (*Infos, error) {
	out := new(Infos)
	err := c.cc.Invoke(ctx, "/appootb.account.Account/GetInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateInfo(ctx context.Context, in *VariableInfo, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/appootb.account.Account/UpdateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// Get account info.
	GetInfo(context.Context, *common.UniqueId) (*Info, error)
	// Get account infos.
	GetInfos(context.Context, *common.UniqueIds) (*Infos, error)
	// Update account info.
	UpdateInfo(context.Context, *VariableInfo) (*Info, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) GetInfo(ctx context.Context, req *common.UniqueId) (*Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedAccountServer) GetInfos(ctx context.Context, req *common.UniqueIds) (*Infos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfos not implemented")
}
func (*UnimplementedAccountServer) UpdateInfo(ctx context.Context, req *VariableInfo) (*Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInfo not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UniqueId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Account/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetInfo(ctx, req.(*common.UniqueId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UniqueIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Account/GetInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetInfos(ctx, req.(*common.UniqueIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariableInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Account/UpdateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateInfo(ctx, req.(*VariableInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Account_GetInfo_Handler,
		},
		{
			MethodName: "GetInfos",
			Handler:    _Account_GetInfos_Handler,
		},
		{
			MethodName: "UpdateInfo",
			Handler:    _Account_UpdateInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
