// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package account

import (
	context "context"
	fmt "fmt"
	captcha "github.com/appootb/protobuf/go/captcha"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Login request.
type LoginRequest struct {
	RelateId *string `protobuf:"bytes,1,req,name=relate_id,json=relateId" json:"relate_id,omitempty"`
	// Types that are valid to be assigned to Secure:
	//	*LoginRequest_Code
	//	*LoginRequest_Password
	Secure               isLoginRequest_Secure `protobuf_oneof:"secure"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetRelateId() string {
	if m != nil && m.RelateId != nil {
		return *m.RelateId
	}
	return ""
}

type isLoginRequest_Secure interface {
	isLoginRequest_Secure()
}

type LoginRequest_Code struct {
	Code string `protobuf:"bytes,2,opt,name=code,oneof"`
}

type LoginRequest_Password struct {
	Password string `protobuf:"bytes,3,opt,name=password,oneof"`
}

func (*LoginRequest_Code) isLoginRequest_Secure() {}

func (*LoginRequest_Password) isLoginRequest_Secure() {}

func (m *LoginRequest) GetSecure() isLoginRequest_Secure {
	if m != nil {
		return m.Secure
	}
	return nil
}

func (m *LoginRequest) GetCode() string {
	if x, ok := m.GetSecure().(*LoginRequest_Code); ok {
		return x.Code
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if x, ok := m.GetSecure().(*LoginRequest_Password); ok {
		return x.Password
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginRequest_Code)(nil),
		(*LoginRequest_Password)(nil),
	}
}

// OAuth request.
type OAuthRequest struct {
	Type                 *AuthType `protobuf:"varint,1,req,name=type,enum=appootb.account.AuthType" json:"type,omitempty"`
	OpenId               *string   `protobuf:"bytes,2,req,name=open_id,json=openId" json:"open_id,omitempty"`
	AccessToken          *string   `protobuf:"bytes,3,req,name=access_token,json=accessToken" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OAuthRequest) Reset()         { *m = OAuthRequest{} }
func (m *OAuthRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthRequest) ProtoMessage()    {}
func (*OAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *OAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthRequest.Unmarshal(m, b)
}
func (m *OAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthRequest.Marshal(b, m, deterministic)
}
func (m *OAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthRequest.Merge(m, src)
}
func (m *OAuthRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthRequest.Size(m)
}
func (m *OAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthRequest proto.InternalMessageInfo

func (m *OAuthRequest) GetType() AuthType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (m *OAuthRequest) GetOpenId() string {
	if m != nil && m.OpenId != nil {
		return *m.OpenId
	}
	return ""
}

func (m *OAuthRequest) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

// Region.
type Region struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Local                *string  `protobuf:"bytes,2,req,name=local" json:"local,omitempty"`
	Abbr                 *string  `protobuf:"bytes,3,req,name=abbr" json:"abbr,omitempty"`
	Code                 *string  `protobuf:"bytes,4,req,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Region) Reset()         { *m = Region{} }
func (m *Region) String() string { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()    {}
func (*Region) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Region) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Region.Unmarshal(m, b)
}
func (m *Region) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Region.Marshal(b, m, deterministic)
}
func (m *Region) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Region.Merge(m, src)
}
func (m *Region) XXX_Size() int {
	return xxx_messageInfo_Region.Size(m)
}
func (m *Region) XXX_DiscardUnknown() {
	xxx_messageInfo_Region.DiscardUnknown(m)
}

var xxx_messageInfo_Region proto.InternalMessageInfo

func (m *Region) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Region) GetLocal() string {
	if m != nil && m.Local != nil {
		return *m.Local
	}
	return ""
}

func (m *Region) GetAbbr() string {
	if m != nil && m.Abbr != nil {
		return *m.Abbr
	}
	return ""
}

func (m *Region) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

// Regions.
type Regions struct {
	Regions              []*Region `protobuf:"bytes,1,rep,name=regions" json:"regions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Regions) Reset()         { *m = Regions{} }
func (m *Regions) String() string { return proto.CompactTextString(m) }
func (*Regions) ProtoMessage()    {}
func (*Regions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Regions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regions.Unmarshal(m, b)
}
func (m *Regions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regions.Marshal(b, m, deterministic)
}
func (m *Regions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regions.Merge(m, src)
}
func (m *Regions) XXX_Size() int {
	return xxx_messageInfo_Regions.Size(m)
}
func (m *Regions) XXX_DiscardUnknown() {
	xxx_messageInfo_Regions.DiscardUnknown(m)
}

var xxx_messageInfo_Regions proto.InternalMessageInfo

func (m *Regions) GetRegions() []*Region {
	if m != nil {
		return m.Regions
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "appootb.account.LoginRequest")
	proto.RegisterType((*OAuthRequest)(nil), "appootb.account.OAuthRequest")
	proto.RegisterType((*Region)(nil), "appootb.account.Region")
	proto.RegisterType((*Regions)(nil), "appootb.account.Regions")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc6, 0x76, 0xda, 0x24, 0xd7, 0x08, 0xa4, 0x6b, 0x4b, 0x8d, 0x9b, 0x42, 0xf1, 0x00, 0x55,
	0x25, 0x6c, 0xd1, 0xb1, 0x62, 0x69, 0x2a, 0xd4, 0x56, 0x42, 0x22, 0xb2, 0x3a, 0x95, 0xa2, 0xea,
	0x72, 0xbe, 0xd8, 0x16, 0xf1, 0x3d, 0xe3, 0x3b, 0xab, 0xca, 0xca, 0x5f, 0x60, 0x65, 0x62, 0xe4,
	0x97, 0x20, 0x56, 0x36, 0x66, 0x7e, 0x44, 0x47, 0x74, 0xe7, 0x73, 0x94, 0x36, 0x84, 0x81, 0x25,
	0xb9, 0xf7, 0xbd, 0xe7, 0xef, 0x7b, 0xf7, 0x7d, 0x4e, 0x10, 0x22, 0x95, 0x4c, 0x83, 0xa2, 0x04,
	0x09, 0xf8, 0x01, 0x29, 0x0a, 0x00, 0x39, 0x0a, 0x08, 0xa5, 0x50, 0x71, 0xe9, 0xf5, 0x0d, 0x10,
	0x52, 0x52, 0x48, 0x9a, 0x92, 0x90, 0x42, 0x9e, 0x03, 0xaf, 0xc7, 0xbd, 0x27, 0x4d, 0xb7, 0x60,
	0x65, 0x9e, 0x09, 0x91, 0x01, 0x0f, 0x73, 0x26, 0x53, 0x88, 0xcd, 0x40, 0x3f, 0x01, 0x48, 0x26,
	0x2c, 0x24, 0x45, 0x16, 0x12, 0xce, 0x41, 0x12, 0x99, 0x01, 0x17, 0xa6, 0xbb, 0x6d, 0xba, 0xba,
	0x1a, 0x55, 0xe3, 0x90, 0xe5, 0x85, 0x9c, 0x9a, 0x66, 0x6f, 0x5e, 0xc9, 0xcf, 0x50, 0xef, 0x0d,
	0x24, 0x19, 0x8f, 0xd8, 0xc7, 0x8a, 0x09, 0x89, 0xb7, 0x51, 0xb7, 0x64, 0x13, 0x22, 0xd9, 0x55,
	0x16, 0xbb, 0xd6, 0xae, 0xbd, 0xd7, 0x8d, 0x3a, 0x35, 0x70, 0x16, 0xe3, 0x0d, 0xd4, 0xa2, 0x10,
	0x33, 0xd7, 0xde, 0xb5, 0xf6, 0xba, 0xa7, 0xf7, 0x22, 0x5d, 0xe1, 0x3e, 0xea, 0x14, 0x44, 0x88,
	0x6b, 0x28, 0x63, 0xd7, 0x31, 0x9d, 0x19, 0x32, 0xe8, 0xa0, 0x55, 0xc1, 0x68, 0x55, 0x32, 0x7f,
	0x8a, 0x7a, 0x6f, 0x8f, 0x2a, 0x99, 0x36, 0x52, 0x2f, 0x50, 0x4b, 0x4e, 0x0b, 0xa6, 0x55, 0xee,
	0x1f, 0x3c, 0x0a, 0xee, 0x58, 0x14, 0xa8, 0xd9, 0xf3, 0x69, 0xc1, 0x22, 0x3d, 0x86, 0xb7, 0x50,
	0x1b, 0x0a, 0xc6, 0xd5, 0x5e, 0xb6, 0xde, 0x6b, 0x55, 0x95, 0x67, 0x31, 0x7e, 0x8a, 0x7a, 0x84,
	0x52, 0x26, 0xc4, 0x95, 0x84, 0x0f, 0x8c, 0xbb, 0x8e, 0xee, 0xae, 0xd5, 0xd8, 0xb9, 0x82, 0xfc,
	0x0b, 0xb4, 0x1a, 0xb1, 0x24, 0x03, 0x8e, 0x31, 0x6a, 0x71, 0x92, 0x33, 0x73, 0x35, 0x7d, 0xc6,
	0x1b, 0x68, 0x65, 0x02, 0x94, 0x4c, 0x0c, 0x6f, 0x5d, 0xa8, 0x49, 0x32, 0x1a, 0x95, 0x86, 0x4e,
	0x9f, 0x15, 0xa6, 0x0d, 0x68, 0xd5, 0x98, 0x3a, 0xfb, 0xaf, 0x50, 0xbb, 0xe6, 0x16, 0xf8, 0x25,
	0x6a, 0x97, 0xf5, 0xd1, 0xb5, 0x76, 0x9d, 0xbd, 0xb5, 0x83, 0xad, 0x85, 0x4b, 0xd5, 0xa3, 0x51,
	0x33, 0x77, 0x70, 0xe3, 0xa0, 0x96, 0xba, 0x28, 0x7e, 0x87, 0xda, 0x27, 0x4c, 0x1e, 0x6b, 0x43,
	0x67, 0x4f, 0x99, 0x97, 0x23, 0x50, 0xb0, 0xb1, 0xcd, 0x7b, 0x18, 0xd4, 0xe9, 0x06, 0x4d, 0xba,
	0xc1, 0x6b, 0x95, 0xae, 0xef, 0x7d, 0xfa, 0xf9, 0xfb, 0xb3, 0xbd, 0x81, 0x71, 0x68, 0xb4, 0x42,
	0xf5, 0xfe, 0x85, 0x3a, 0xa2, 0x18, 0xad, 0xe8, 0x94, 0xf1, 0xce, 0xc2, 0x42, 0xf3, 0xe9, 0x7b,
	0xfd, 0xc5, 0x10, 0xea, 0xef, 0x33, 0x3e, 0x06, 0xff, 0xb1, 0x56, 0x70, 0xfd, 0xf5, 0xdb, 0x0a,
	0x13, 0xc5, 0x70, 0x68, 0xed, 0x2b, 0x15, 0x1d, 0xf0, 0x5f, 0x54, 0xe6, 0x83, 0xff, 0x3f, 0x15,
	0x50, 0x9f, 0x4a, 0xe5, 0x3d, 0x42, 0x27, 0x4c, 0x36, 0x96, 0x2f, 0x71, 0xc3, 0x73, 0x97, 0x38,
	0x2f, 0xfc, 0x1d, 0xcd, 0xbf, 0x85, 0x37, 0x6f, 0xf3, 0x9b, 0x40, 0x70, 0xaa, 0xe2, 0x1c, 0x97,
	0x4c, 0xa4, 0x4b, 0xb9, 0xff, 0xbd, 0xff, 0xf3, 0x5f, 0x5f, 0x2c, 0xa7, 0xf3, 0xdd, 0xd2, 0x32,
	0x9e, 0xb7, 0x20, 0xa3, 0xb9, 0x0f, 0xad, 0xfd, 0xc1, 0x35, 0x5a, 0xa7, 0x90, 0xdf, 0xe5, 0x1a,
	0x74, 0x95, 0x55, 0x43, 0xa5, 0x78, 0x6a, 0x0d, 0xad, 0x8b, 0x67, 0x49, 0x26, 0xd3, 0x6a, 0x14,
	0x50, 0xc8, 0xc3, 0xd9, 0xbf, 0x42, 0xf3, 0xbb, 0x4e, 0xa0, 0x61, 0xbf, 0xb1, 0xac, 0xaf, 0xb6,
	0x73, 0x3c, 0x1c, 0x7c, 0xb3, 0xdb, 0x66, 0x9b, 0x1f, 0xf6, 0xe6, 0x51, 0xfd, 0xc0, 0xa5, 0xa6,
	0xbb, 0x34, 0xf8, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0xf3, 0x9f, 0x04, 0x99, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// Get auth code.
	GetCode(ctx context.Context, in *captcha.CodeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Login.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AccountInfo, error)
	// OAuth.
	OAuth(ctx context.Context, in *OAuthRequest, opts ...grpc.CallOption) (*AccountInfo, error)
	// Get regions.
	GetRegions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Regions, error)
	// Refresh account token.
	Refresh(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AccountInfo, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetCode(ctx context.Context, in *captcha.CodeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appootb.account.Auth/GetCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AccountInfo, error) {
	out := new(AccountInfo)
	err := c.cc.Invoke(ctx, "/appootb.account.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) OAuth(ctx context.Context, in *OAuthRequest, opts ...grpc.CallOption) (*AccountInfo, error) {
	out := new(AccountInfo)
	err := c.cc.Invoke(ctx, "/appootb.account.Auth/OAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetRegions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Regions, error) {
	out := new(Regions)
	err := c.cc.Invoke(ctx, "/appootb.account.Auth/GetRegions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Refresh(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AccountInfo, error) {
	out := new(AccountInfo)
	err := c.cc.Invoke(ctx, "/appootb.account.Auth/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// Get auth code.
	GetCode(context.Context, *captcha.CodeRequest) (*empty.Empty, error)
	// Login.
	Login(context.Context, *LoginRequest) (*AccountInfo, error)
	// OAuth.
	OAuth(context.Context, *OAuthRequest) (*AccountInfo, error)
	// Get regions.
	GetRegions(context.Context, *empty.Empty) (*Regions, error)
	// Refresh account token.
	Refresh(context.Context, *empty.Empty) (*AccountInfo, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) GetCode(ctx context.Context, req *captcha.CodeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCode not implemented")
}
func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginRequest) (*AccountInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) OAuth(ctx context.Context, req *OAuthRequest) (*AccountInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OAuth not implemented")
}
func (*UnimplementedAuthServer) GetRegions(ctx context.Context, req *empty.Empty) (*Regions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegions not implemented")
}
func (*UnimplementedAuthServer) Refresh(ctx context.Context, req *empty.Empty) (*AccountInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_GetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(captcha.CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Auth/GetCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetCode(ctx, req.(*captcha.CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_OAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).OAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Auth/OAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).OAuth(ctx, req.(*OAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Auth/GetRegions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetRegions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Auth/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Refresh(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.account.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCode",
			Handler:    _Auth_GetCode_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "OAuth",
			Handler:    _Auth_OAuth_Handler,
		},
		{
			MethodName: "GetRegions",
			Handler:    _Auth_GetRegions_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Auth_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
