// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bind.proto

package account

import (
	context "context"
	fmt "fmt"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Account binding information.
type Binding struct {
	SourceType           *AuthType `protobuf:"varint,1,req,name=source_type,json=sourceType,enum=appootb.account.AuthType" json:"source_type,omitempty"`
	SourceId             *string   `protobuf:"bytes,2,req,name=source_id,json=sourceId" json:"source_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Binding) Reset()         { *m = Binding{} }
func (m *Binding) String() string { return proto.CompactTextString(m) }
func (*Binding) ProtoMessage()    {}
func (*Binding) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ba67facb4874d5, []int{0}
}

func (m *Binding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binding.Unmarshal(m, b)
}
func (m *Binding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binding.Marshal(b, m, deterministic)
}
func (m *Binding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binding.Merge(m, src)
}
func (m *Binding) XXX_Size() int {
	return xxx_messageInfo_Binding.Size(m)
}
func (m *Binding) XXX_DiscardUnknown() {
	xxx_messageInfo_Binding.DiscardUnknown(m)
}

var xxx_messageInfo_Binding proto.InternalMessageInfo

func (m *Binding) GetSourceType() AuthType {
	if m != nil && m.SourceType != nil {
		return *m.SourceType
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (m *Binding) GetSourceId() string {
	if m != nil && m.SourceId != nil {
		return *m.SourceId
	}
	return ""
}

// Account binding request.
type BindRequest struct {
	Bind                 *Binding `protobuf:"bytes,1,req,name=bind" json:"bind,omitempty"`
	Code                 *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindRequest) Reset()         { *m = BindRequest{} }
func (m *BindRequest) String() string { return proto.CompactTextString(m) }
func (*BindRequest) ProtoMessage()    {}
func (*BindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ba67facb4874d5, []int{1}
}

func (m *BindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindRequest.Unmarshal(m, b)
}
func (m *BindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindRequest.Marshal(b, m, deterministic)
}
func (m *BindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindRequest.Merge(m, src)
}
func (m *BindRequest) XXX_Size() int {
	return xxx_messageInfo_BindRequest.Size(m)
}
func (m *BindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindRequest proto.InternalMessageInfo

func (m *BindRequest) GetBind() *Binding {
	if m != nil {
		return m.Bind
	}
	return nil
}

func (m *BindRequest) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

// Account bindings.
type Bindings struct {
	Binds                []*Binding `protobuf:"bytes,1,rep,name=binds" json:"binds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bindings) Reset()         { *m = Bindings{} }
func (m *Bindings) String() string { return proto.CompactTextString(m) }
func (*Bindings) ProtoMessage()    {}
func (*Bindings) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ba67facb4874d5, []int{2}
}

func (m *Bindings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bindings.Unmarshal(m, b)
}
func (m *Bindings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bindings.Marshal(b, m, deterministic)
}
func (m *Bindings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bindings.Merge(m, src)
}
func (m *Bindings) XXX_Size() int {
	return xxx_messageInfo_Bindings.Size(m)
}
func (m *Bindings) XXX_DiscardUnknown() {
	xxx_messageInfo_Bindings.DiscardUnknown(m)
}

var xxx_messageInfo_Bindings proto.InternalMessageInfo

func (m *Bindings) GetBinds() []*Binding {
	if m != nil {
		return m.Binds
	}
	return nil
}

func init() {
	proto.RegisterType((*Binding)(nil), "appootb.account.Binding")
	proto.RegisterType((*BindRequest)(nil), "appootb.account.BindRequest")
	proto.RegisterType((*Bindings)(nil), "appootb.account.Bindings")
}

func init() { proto.RegisterFile("bind.proto", fileDescriptor_93ba67facb4874d5) }

var fileDescriptor_93ba67facb4874d5 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3d, 0x6f, 0x13, 0x31,
	0x18, 0x96, 0xdd, 0x2b, 0x6d, 0xde, 0xa8, 0x2d, 0x32, 0x02, 0x5d, 0xd3, 0x8a, 0x86, 0x1b, 0x50,
	0x54, 0x21, 0x9f, 0x94, 0x31, 0x13, 0x49, 0x85, 0x80, 0x89, 0xe8, 0xc4, 0x54, 0x55, 0xc0, 0x7d,
	0x98, 0x8b, 0xa5, 0x9c, 0x5f, 0x13, 0xfb, 0x84, 0xb2, 0x21, 0xfe, 0x02, 0x6b, 0x27, 0xc4, 0xc4,
	0x4f, 0x61, 0x65, 0xe9, 0x0f, 0xe0, 0x47, 0x30, 0x22, 0xdf, 0x39, 0x48, 0x57, 0x28, 0x03, 0x9b,
	0xfd, 0xbc, 0xcf, 0xc7, 0xeb, 0x47, 0x06, 0xc8, 0xa4, 0x2a, 0xb8, 0x5e, 0xa1, 0x45, 0x76, 0x90,
	0x6a, 0x8d, 0x68, 0x33, 0x9e, 0xe6, 0x39, 0xd6, 0xca, 0x0e, 0x4e, 0x3c, 0x10, 0x6b, 0xb1, 0xaa,
	0xa4, 0x31, 0x12, 0x55, 0x5c, 0x09, 0xbb, 0x40, 0xaf, 0x18, 0x1c, 0x97, 0x88, 0xe5, 0x52, 0xc4,
	0xa9, 0x96, 0x71, 0xaa, 0x14, 0xda, 0xd4, 0x4a, 0x54, 0xc6, 0x4f, 0x8f, 0xfc, 0xb4, 0xb9, 0x65,
	0xf5, 0xdb, 0x58, 0x54, 0xda, 0xae, 0xfd, 0x70, 0x4f, 0xaa, 0x7c, 0x59, 0x17, 0xa2, 0xbd, 0x46,
	0x19, 0xec, 0xcc, 0xa4, 0x2a, 0xa4, 0x2a, 0xd9, 0x04, 0xfa, 0x06, 0xeb, 0x55, 0x2e, 0x5e, 0xdb,
	0xb5, 0x16, 0x21, 0x19, 0xd2, 0xd1, 0xfe, 0xf8, 0x90, 0x5f, 0x5b, 0x8e, 0x4f, 0x6b, 0xbb, 0x78,
	0xb9, 0xd6, 0x22, 0x81, 0x96, 0xed, 0xce, 0xec, 0x08, 0x7a, 0x5e, 0x2b, 0x8b, 0x90, 0x0e, 0xe9,
	0xa8, 0x97, 0xec, 0xb6, 0xc0, 0xf3, 0x22, 0x7a, 0x01, 0x7d, 0x97, 0x91, 0x88, 0x77, 0xb5, 0x30,
	0x96, 0x3d, 0x82, 0xc0, 0x3d, 0xbe, 0x09, 0xe8, 0x8f, 0xc3, 0x3f, 0x02, 0xfc, 0x3e, 0x49, 0xc3,
	0x62, 0x0c, 0x82, 0x1c, 0x0b, 0x11, 0xd2, 0x21, 0x19, 0xf5, 0x92, 0xe6, 0x1c, 0x4d, 0x60, 0xd7,
	0x93, 0x0c, 0xe3, 0xb0, 0xed, 0x78, 0x26, 0x24, 0xc3, 0xad, 0x7f, 0xda, 0xb5, 0xb4, 0xf1, 0x17,
	0x0a, 0x81, 0x83, 0xd8, 0x1b, 0xd8, 0x9e, 0x6a, 0xbd, 0x5c, 0xb3, 0xe3, 0xbf, 0x4a, 0xfc, 0xb6,
	0x83, 0x7b, 0xbc, 0x6d, 0x93, 0x6f, 0xda, 0xe4, 0x4f, 0x5c, 0x9b, 0xd1, 0x83, 0xab, 0x4b, 0xf2,
	0xf8, 0xea, 0x92, 0x7c, 0x08, 0x3e, 0x7e, 0xff, 0xf1, 0x89, 0xb2, 0x68, 0x2f, 0xf6, 0xf2, 0xd8,
	0x05, 0x4d, 0xc8, 0x29, 0x7b, 0x05, 0xb7, 0xce, 0x52, 0x95, 0x8b, 0xe5, 0x7f, 0x46, 0xdc, 0xef,
	0x46, 0x1c, 0x9c, 0x76, 0x23, 0xd8, 0x39, 0x04, 0x4f, 0x85, 0x35, 0xec, 0x06, 0xfd, 0xe0, 0xf0,
	0xa6, 0x2e, 0x4c, 0x74, 0xd2, 0xb5, 0xbe, 0xcd, 0xf6, 0x3b, 0xd6, 0x66, 0xf6, 0x1e, 0xee, 0xe4,
	0x58, 0x5d, 0x37, 0x98, 0xf5, 0x9c, 0xc3, 0xdc, 0xc5, 0x3c, 0x23, 0x73, 0x72, 0xfe, 0xb0, 0x94,
	0x76, 0x51, 0x67, 0x3c, 0xc7, 0x2a, 0xfe, 0xfd, 0x67, 0x37, 0xbf, 0xae, 0xc4, 0x8d, 0xe7, 0x4f,
	0x42, 0x3e, 0xd3, 0xad, 0xb3, 0xf9, 0xec, 0x2b, 0xdd, 0x99, 0xb6, 0xd0, 0x37, 0x7a, 0x77, 0xda,
	0x0a, 0x2e, 0x1a, 0xbb, 0x0b, 0x8f, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x95, 0x5f, 0x09, 0x55,
	0x19, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BindClient is the client API for Bind service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BindClient interface {
	// Apply account bind.
	Apply(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Cancel account bind.
	Cancel(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get all bind info.
	Gets(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Bindings, error)
}

type bindClient struct {
	cc *grpc.ClientConn
}

func NewBindClient(cc *grpc.ClientConn) BindClient {
	return &bindClient{cc}
}

func (c *bindClient) Apply(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appootb.account.Bind/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindClient) Cancel(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appootb.account.Bind/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindClient) Gets(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Bindings, error) {
	out := new(Bindings)
	err := c.cc.Invoke(ctx, "/appootb.account.Bind/Gets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BindServer is the server API for Bind service.
type BindServer interface {
	// Apply account bind.
	Apply(context.Context, *BindRequest) (*empty.Empty, error)
	// Cancel account bind.
	Cancel(context.Context, *BindRequest) (*empty.Empty, error)
	// Get all bind info.
	Gets(context.Context, *empty.Empty) (*Bindings, error)
}

// UnimplementedBindServer can be embedded to have forward compatible implementations.
type UnimplementedBindServer struct {
}

func (*UnimplementedBindServer) Apply(ctx context.Context, req *BindRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (*UnimplementedBindServer) Cancel(ctx context.Context, req *BindRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (*UnimplementedBindServer) Gets(ctx context.Context, req *empty.Empty) (*Bindings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gets not implemented")
}

func RegisterBindServer(s *grpc.Server, srv BindServer) {
	s.RegisterService(&_Bind_serviceDesc, srv)
}

func _Bind_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Bind/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindServer).Apply(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bind_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Bind/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindServer).Cancel(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bind_Gets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindServer).Gets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Bind/Gets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindServer).Gets(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bind_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.account.Bind",
	HandlerType: (*BindServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Bind_Apply_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Bind_Cancel_Handler,
		},
		{
			MethodName: "Gets",
			Handler:    _Bind_Gets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bind.proto",
}
