// Code generated by protoc-gen-go. DO NOT EDIT.
// source: include.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Account gender enums.
type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
	Gender_GENDER_OTHER       Gender = 3
)

var Gender_name = map[int32]string{
	0: "GENDER_UNSPECIFIED",
	1: "GENDER_MALE",
	2: "GENDER_FEMALE",
	3: "GENDER_OTHER",
}

var Gender_value = map[string]int32{
	"GENDER_UNSPECIFIED": 0,
	"GENDER_MALE":        1,
	"GENDER_FEMALE":      2,
	"GENDER_OTHER":       3,
}

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (x *Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gender_value, data, "Gender")
	if err != nil {
		return err
	}
	*x = Gender(value)
	return nil
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{0}
}

// Auth source enums.
type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED AuthType = 0
	AuthType_AUTH_TYPE_APPLE_ID    AuthType = 1
	AuthType_AUTH_TYPE_ACCOUNT     AuthType = 2
	AuthType_AUTH_TYPE_WECHAT      AuthType = 3
	AuthType_AUTH_TYPE_QQ          AuthType = 4
	AuthType_AUTH_TYPE_WEIBO       AuthType = 5
)

var AuthType_name = map[int32]string{
	0: "AUTH_TYPE_UNSPECIFIED",
	1: "AUTH_TYPE_APPLE_ID",
	2: "AUTH_TYPE_ACCOUNT",
	3: "AUTH_TYPE_WECHAT",
	4: "AUTH_TYPE_QQ",
	5: "AUTH_TYPE_WEIBO",
}

var AuthType_value = map[string]int32{
	"AUTH_TYPE_UNSPECIFIED": 0,
	"AUTH_TYPE_APPLE_ID":    1,
	"AUTH_TYPE_ACCOUNT":     2,
	"AUTH_TYPE_WECHAT":      3,
	"AUTH_TYPE_QQ":          4,
	"AUTH_TYPE_WEIBO":       5,
}

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return proto.EnumName(AuthType_name, int32(x))
}

func (x *AuthType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthType_value, data, "AuthType")
	if err != nil {
		return err
	}
	*x = AuthType(value)
	return nil
}

func (AuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{1}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_BLOCKED     Status = 2
)

var Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_ACTIVE",
	2: "STATUS_BLOCKED",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_ACTIVE":      1,
	"STATUS_BLOCKED":     2,
}

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (x *Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Status_value, data, "Status")
	if err != nil {
		return err
	}
	*x = Status(value)
	return nil
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{2}
}

// Account secret.
type Secret struct {
	Token                *string  `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{0}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// Account information.
type Info struct {
	UniqueId             *uint64              `protobuf:"varint,1,req,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	Nickname             *string              `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	Avatar               *string              `protobuf:"bytes,3,req,name=avatar" json:"avatar,omitempty"`
	Status               *Status              `protobuf:"varint,4,req,name=status,enum=appootb.account.Status" json:"status,omitempty"`
	Signature            *string              `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
	Gender               *Gender              `protobuf:"varint,6,opt,name=gender,enum=appootb.account.Gender" json:"gender,omitempty"`
	Signs                *string              `protobuf:"bytes,7,opt,name=signs" json:"signs,omitempty"`
	Location             *string              `protobuf:"bytes,8,opt,name=location" json:"location,omitempty"`
	Secret               *Secret              `protobuf:"bytes,9,opt,name=secret" json:"secret,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,97,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,98,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Extend               *any.Any             `protobuf:"bytes,99,opt,name=extend" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{1}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetUniqueId() uint64 {
	if m != nil && m.UniqueId != nil {
		return *m.UniqueId
	}
	return 0
}

func (m *Info) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *Info) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *Info) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (m *Info) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *Info) GetGender() Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (m *Info) GetSigns() string {
	if m != nil && m.Signs != nil {
		return *m.Signs
	}
	return ""
}

func (m *Info) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *Info) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *Info) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Info) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Info) GetExtend() *any.Any {
	if m != nil {
		return m.Extend
	}
	return nil
}

// Accounts information.
type Infos struct {
	Accounts             map[uint64]*Info `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Infos) Reset()         { *m = Infos{} }
func (m *Infos) String() string { return proto.CompactTextString(m) }
func (*Infos) ProtoMessage()    {}
func (*Infos) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{2}
}

func (m *Infos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Infos.Unmarshal(m, b)
}
func (m *Infos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Infos.Marshal(b, m, deterministic)
}
func (m *Infos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Infos.Merge(m, src)
}
func (m *Infos) XXX_Size() int {
	return xxx_messageInfo_Infos.Size(m)
}
func (m *Infos) XXX_DiscardUnknown() {
	xxx_messageInfo_Infos.DiscardUnknown(m)
}

var xxx_messageInfo_Infos proto.InternalMessageInfo

func (m *Infos) GetAccounts() map[uint64]*Info {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterEnum("appootb.account.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("appootb.account.AuthType", AuthType_name, AuthType_value)
	proto.RegisterEnum("appootb.account.Status", Status_name, Status_value)
	proto.RegisterType((*Secret)(nil), "appootb.account.Secret")
	proto.RegisterType((*Info)(nil), "appootb.account.Info")
	proto.RegisterType((*Infos)(nil), "appootb.account.Infos")
	proto.RegisterMapType((map[uint64]*Info)(nil), "appootb.account.Infos.AccountsEntry")
}

func init() { proto.RegisterFile("include.proto", fileDescriptor_f1eef7b97e24a48e) }

var fileDescriptor_f1eef7b97e24a48e = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xda, 0x4a,
	0x14, 0xc6, 0xef, 0x98, 0x3f, 0x81, 0xc3, 0x25, 0x71, 0x26, 0x21, 0xd7, 0xe1, 0x56, 0x2d, 0x8a,
	0xaa, 0x0a, 0xa5, 0x95, 0x91, 0xb2, 0x6a, 0xbb, 0xaa, 0x31, 0x4e, 0x40, 0x4d, 0x03, 0x19, 0x4c,
	0xaa, 0x56, 0x91, 0xd0, 0x60, 0x26, 0xc4, 0x0a, 0xcc, 0x50, 0x18, 0x47, 0xe5, 0x31, 0xfa, 0x00,
	0xdd, 0x74, 0xd9, 0x47, 0xe9, 0x43, 0xf4, 0x39, 0xba, 0xac, 0x3c, 0x9e, 0x84, 0x94, 0x44, 0xea,
	0x8e, 0xf3, 0x7d, 0xbf, 0xef, 0xcc, 0x1c, 0x9f, 0x11, 0x50, 0x0c, 0x79, 0x30, 0x8e, 0x86, 0xcc,
	0x9e, 0xce, 0x84, 0x14, 0x78, 0x83, 0x4e, 0xa7, 0x42, 0xc8, 0x81, 0x4d, 0x83, 0x40, 0x44, 0x5c,
	0x96, 0x77, 0x47, 0x42, 0x8c, 0xc6, 0xac, 0xa6, 0xec, 0x41, 0x74, 0x51, 0xa3, 0x7c, 0x91, 0xb0,
	0xe5, 0x27, 0xab, 0x96, 0x0c, 0x27, 0x6c, 0x2e, 0xe9, 0x64, 0x9a, 0x00, 0x7b, 0x8f, 0x21, 0xdb,
	0x65, 0xc1, 0x8c, 0x49, 0xbc, 0x0d, 0x19, 0x29, 0xae, 0x18, 0xb7, 0x50, 0xc5, 0xa8, 0xe6, 0x49,
	0x52, 0xec, 0xfd, 0x4c, 0x41, 0xba, 0xc5, 0x2f, 0x04, 0xfe, 0x1f, 0xf2, 0x11, 0x0f, 0x3f, 0x45,
	0xac, 0x1f, 0x0e, 0x15, 0x92, 0x26, 0xb9, 0x44, 0x68, 0x0d, 0x71, 0x19, 0x72, 0x3c, 0x0c, 0xae,
	0x38, 0x9d, 0x30, 0xcb, 0x50, 0xf1, 0xdb, 0x1a, 0xef, 0x40, 0x96, 0x5e, 0x53, 0x49, 0x67, 0x56,
	0x4a, 0x39, 0xba, 0xc2, 0x35, 0xc8, 0xce, 0x25, 0x95, 0xd1, 0xdc, 0x4a, 0x57, 0x8c, 0xea, 0xfa,
	0xc1, 0x7f, 0xf6, 0xca, 0x5c, 0x76, 0x57, 0xd9, 0x44, 0x63, 0xf8, 0x11, 0xe4, 0xe7, 0xe1, 0x88,
	0x53, 0x19, 0xcd, 0x98, 0x95, 0xa9, 0xa0, 0x6a, 0x9e, 0x2c, 0x85, 0xb8, 0xdd, 0x88, 0xf1, 0x21,
	0x9b, 0x59, 0xd9, 0x0a, 0x7a, 0xb0, 0xdd, 0x91, 0xb2, 0x89, 0xc6, 0xe2, 0x79, 0xe3, 0xf4, 0xdc,
	0x5a, 0x53, 0xad, 0x92, 0x22, 0x9e, 0x64, 0x2c, 0x02, 0x2a, 0x43, 0xc1, 0xad, 0x9c, 0x32, 0x6e,
	0x6b, 0x75, 0x63, 0xf5, 0xad, 0xac, 0x7c, 0x05, 0x55, 0x0b, 0x0f, 0xdd, 0x58, 0xd9, 0x44, 0x63,
	0xf8, 0x15, 0x40, 0x30, 0x63, 0x54, 0xb2, 0x61, 0x9f, 0x4a, 0x8b, 0xaa, 0x50, 0xd9, 0x4e, 0x56,
	0x62, 0xdf, 0xac, 0xc4, 0xf6, 0x6f, 0x56, 0x42, 0xf2, 0x9a, 0x76, 0x54, 0x34, 0x9a, 0x0e, 0x6f,
	0xa2, 0x83, 0xbf, 0x47, 0x35, 0xed, 0x48, 0xfc, 0x02, 0xb2, 0xec, 0xb3, 0x64, 0x7c, 0x68, 0x05,
	0x2a, 0xb6, 0x7d, 0x2f, 0xe6, 0xf0, 0x05, 0xd1, 0xcc, 0xde, 0x57, 0x04, 0x99, 0x78, 0xc1, 0x73,
	0xfc, 0x06, 0x72, 0x7a, 0x8e, 0xb9, 0x85, 0x2a, 0xa9, 0x6a, 0xe1, 0xe0, 0xe9, 0xbd, 0x01, 0x15,
	0x69, 0x3b, 0x1a, 0xf3, 0xb8, 0x9c, 0x2d, 0xc8, 0x6d, 0xaa, 0x4c, 0xa0, 0xf8, 0x87, 0x85, 0x4d,
	0x48, 0x5d, 0xb1, 0x85, 0x85, 0x2a, 0xa8, 0x9a, 0x26, 0xf1, 0x4f, 0xfc, 0x1c, 0x32, 0xd7, 0x74,
	0x1c, 0xc5, 0xcf, 0x24, 0xbe, 0x5b, 0xe9, 0xc1, 0x13, 0x48, 0xc2, 0xbc, 0x36, 0x5e, 0xa2, 0xfd,
	0x33, 0xc8, 0x26, 0x8b, 0xc3, 0x3b, 0x80, 0x8f, 0xbc, 0x93, 0x86, 0x47, 0xfa, 0xbd, 0x93, 0x6e,
	0xc7, 0x73, 0x5b, 0x87, 0x2d, 0xaf, 0x61, 0xfe, 0x83, 0x37, 0xa0, 0xa0, 0xf5, 0x77, 0xce, 0xb1,
	0x67, 0x22, 0xbc, 0x09, 0x45, 0x2d, 0x1c, 0x7a, 0x4a, 0x32, 0xb0, 0x09, 0xff, 0x6a, 0xa9, 0xed,
	0x37, 0x3d, 0x62, 0xa6, 0xf6, 0xbf, 0x20, 0xc8, 0x39, 0x91, 0xbc, 0xf4, 0x17, 0x53, 0x86, 0x77,
	0xa1, 0xe4, 0xf4, 0xfc, 0x66, 0xdf, 0xff, 0xd0, 0xf1, 0x56, 0xba, 0xef, 0x00, 0x5e, 0x5a, 0x4e,
	0xa7, 0x73, 0xec, 0xf5, 0x5b, 0x0d, 0x13, 0xe1, 0x12, 0x6c, 0xde, 0xd1, 0x5d, 0xb7, 0xdd, 0x3b,
	0xf1, 0x4d, 0x03, 0x6f, 0x83, 0xb9, 0x94, 0xdf, 0x7b, 0x6e, 0xd3, 0xf1, 0xcd, 0x54, 0x7c, 0xfc,
	0x52, 0x3d, 0x3d, 0x35, 0xd3, 0x78, 0x0b, 0x36, 0xee, 0x72, 0xad, 0x7a, 0xdb, 0xcc, 0xec, 0x1f,
	0x41, 0x36, 0x79, 0xf3, 0xf1, 0xa9, 0x5d, 0xdf, 0xf1, 0x7b, 0xdd, 0x95, 0xdb, 0x6c, 0x42, 0x51,
	0xeb, 0x8e, 0xeb, 0xb7, 0xce, 0xe2, 0x69, 0x31, 0xac, 0x6b, 0xa9, 0x7e, 0xdc, 0x76, 0xdf, 0x7a,
	0x0d, 0xd3, 0xa8, 0x2f, 0x60, 0x2b, 0x10, 0x93, 0xd5, 0x6f, 0x5b, 0x2f, 0xb8, 0x62, 0x32, 0x11,
	0xbc, 0x13, 0xbf, 0x83, 0x26, 0xea, 0xa0, 0x8f, 0xcf, 0x46, 0xa1, 0xbc, 0x8c, 0x06, 0x76, 0x20,
	0x26, 0x35, 0x0d, 0x2f, 0xff, 0x2a, 0x46, 0xa2, 0xa6, 0x83, 0xbf, 0x10, 0xfa, 0x66, 0xa4, 0xdc,
	0x4e, 0xfd, 0xbb, 0xb1, 0xa6, 0x17, 0xfc, 0xc3, 0x28, 0x39, 0x49, 0xe0, 0x5c, 0xb5, 0x3b, 0xd7,
	0xfa, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x1f, 0x0c, 0xa2, 0xad, 0x04, 0x00, 0x00,
}
