// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_secret.proto

package account

import (
	context "context"
	fmt "fmt"
	permission "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("inner_secret.proto", fileDescriptor_7a83fd0678beaecd) }

var fileDescriptor_7a83fd0678beaecd = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcc, 0xcb, 0x4b,
	0x2d, 0x8a, 0x2f, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x4f, 0x2c, 0x28, 0xc8, 0xcf, 0x2f, 0x49, 0xd2, 0x4b, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x91,
	0x92, 0x87, 0x0a, 0xe8, 0x17, 0xa4, 0x16, 0xe5, 0x66, 0x16, 0x17, 0x67, 0xe6, 0xe7, 0xe9, 0x23,
	0xeb, 0x90, 0x52, 0xc0, 0xaa, 0xa0, 0xa8, 0x2c, 0x33, 0x39, 0x15, 0xaa, 0x42, 0x26, 0x3d, 0x3f,
	0x3f, 0x3d, 0x27, 0x55, 0x3f, 0xb1, 0x20, 0x53, 0x3f, 0x31, 0x2f, 0x2f, 0xbf, 0x24, 0xb1, 0x24,
	0x33, 0x3f, 0xaf, 0x18, 0x2a, 0xcb, 0x93, 0x9c, 0x9f, 0x9b, 0x9b, 0x9f, 0x07, 0xe1, 0x19, 0xb5,
	0x31, 0x72, 0x71, 0x7b, 0x82, 0x9c, 0x15, 0x0c, 0xb6, 0x43, 0xa8, 0x80, 0x8b, 0xd7, 0x3d, 0xb5,
	0x04, 0xc2, 0xf1, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xd7, 0x43, 0x73, 0xa1, 0x1e, 0x44, 0x52, 0x4a,
	0x09, 0x2e, 0x81, 0x70, 0x08, 0x9a, 0x1a, 0x25, 0xa5, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xc9, 0x08,
	0x49, 0xe9, 0x43, 0x25, 0xf4, 0xc1, 0x41, 0x00, 0xf5, 0x90, 0x7e, 0x66, 0x5e, 0x5a, 0xbe, 0x14,
	0xeb, 0xac, 0x38, 0x26, 0x8e, 0x14, 0xa7, 0x3a, 0x2e, 0xe1, 0xe4, 0xfc, 0x5c, 0x74, 0xcb, 0x9c,
	0x04, 0x90, 0x1c, 0x17, 0x00, 0x72, 0xb1, 0x07, 0x63, 0x00, 0x63, 0x94, 0x5a, 0x7a, 0x66, 0x49,
	0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x3c, 0x38, 0x40, 0xb2, 0x49, 0xa5, 0x69, 0xfa,
	0xe9, 0xf9, 0x30, 0xdb, 0x7e, 0x30, 0x32, 0x2e, 0x62, 0x62, 0x76, 0x0e, 0x70, 0x5a, 0xc5, 0xc4,
	0xee, 0x08, 0x11, 0x3a, 0xc5, 0x24, 0xea, 0x08, 0xd1, 0x10, 0x03, 0x36, 0x2e, 0x06, 0x2a, 0x0e,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x38, 0xee, 0x9c, 0xec, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InnerSecretClient is the client API for InnerSecret service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnerSecretClient interface {
	// Get token info.
	GetSecretInfo(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*permission.Secret, error)
}

type innerSecretClient struct {
	cc *grpc.ClientConn
}

func NewInnerSecretClient(cc *grpc.ClientConn) InnerSecretClient {
	return &innerSecretClient{cc}
}

func (c *innerSecretClient) GetSecretInfo(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*permission.Secret, error) {
	out := new(permission.Secret)
	err := c.cc.Invoke(ctx, "/appootb.account.InnerSecret/GetSecretInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerSecretServer is the server API for InnerSecret service.
type InnerSecretServer interface {
	// Get token info.
	GetSecretInfo(context.Context, *Secret) (*permission.Secret, error)
}

// UnimplementedInnerSecretServer can be embedded to have forward compatible implementations.
type UnimplementedInnerSecretServer struct {
}

func (*UnimplementedInnerSecretServer) GetSecretInfo(ctx context.Context, req *Secret) (*permission.Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecretInfo not implemented")
}

func RegisterInnerSecretServer(s *grpc.Server, srv InnerSecretServer) {
	s.RegisterService(&_InnerSecret_serviceDesc, srv)
}

func _InnerSecret_GetSecretInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerSecretServer).GetSecretInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.InnerSecret/GetSecretInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerSecretServer).GetSecretInfo(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerSecret_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.account.InnerSecret",
	HandlerType: (*InnerSecretServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecretInfo",
			Handler:    _InnerSecret_GetSecretInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_secret.proto",
}
