// Code generated by protoc-gen-go. DO NOT EDIT.
// source: password.proto

package account

import (
	context "context"
	fmt "fmt"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Account password request.
type PasswordRequest struct {
	Password             *string  `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	OldPassword          *string  `protobuf:"bytes,2,opt,name=old_password,json=oldPassword" json:"old_password,omitempty"`
	VerifyCode           *string  `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode" json:"verify_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordRequest) Reset()         { *m = PasswordRequest{} }
func (m *PasswordRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordRequest) ProtoMessage()    {}
func (*PasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3819adb3c6759fd8, []int{0}
}

func (m *PasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordRequest.Unmarshal(m, b)
}
func (m *PasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordRequest.Marshal(b, m, deterministic)
}
func (m *PasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordRequest.Merge(m, src)
}
func (m *PasswordRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordRequest.Size(m)
}
func (m *PasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordRequest proto.InternalMessageInfo

func (m *PasswordRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *PasswordRequest) GetOldPassword() string {
	if m != nil && m.OldPassword != nil {
		return *m.OldPassword
	}
	return ""
}

func (m *PasswordRequest) GetVerifyCode() string {
	if m != nil && m.VerifyCode != nil {
		return *m.VerifyCode
	}
	return ""
}

func init() {
	proto.RegisterType((*PasswordRequest)(nil), "appootb.account.PasswordRequest")
}

func init() { proto.RegisterFile("password.proto", fileDescriptor_3819adb3c6759fd8) }

var fileDescriptor_3819adb3c6759fd8 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xbd, 0x4e, 0xfa, 0x50,
	0x14, 0xcf, 0x2d, 0xff, 0x0f, 0xb8, 0x88, 0xc4, 0x1a, 0x95, 0x34, 0x24, 0x20, 0x89, 0x86, 0x38,
	0xf4, 0x26, 0x8c, 0x4e, 0x02, 0x8b, 0x63, 0x53, 0xe2, 0x62, 0x48, 0xb0, 0xb4, 0x87, 0x52, 0xd3,
	0xf6, 0x5c, 0x7a, 0x6f, 0x35, 0xc6, 0xc5, 0xf8, 0x0a, 0xae, 0x4c, 0x8e, 0xbe, 0x85, 0xab, 0xab,
	0x0b, 0x0f, 0xe0, 0x43, 0x38, 0x1a, 0xe8, 0xc7, 0x80, 0x6c, 0x3a, 0x9e, 0xdf, 0xf9, 0x7d, 0x9d,
	0xdc, 0x4b, 0xb7, 0xb9, 0x25, 0xc4, 0x2d, 0x46, 0x8e, 0xce, 0x23, 0x94, 0xa8, 0x56, 0x2d, 0xce,
	0x11, 0xe5, 0x58, 0xb7, 0x6c, 0x1b, 0xe3, 0x50, 0x6a, 0x8d, 0x14, 0x60, 0x1c, 0xa2, 0xc0, 0x13,
	0xc2, 0xc3, 0x90, 0x05, 0x20, 0xa7, 0x98, 0x2a, 0xb4, 0xba, 0x8b, 0xe8, 0xfa, 0xc0, 0x2c, 0xee,
	0x31, 0x2b, 0x0c, 0x51, 0x5a, 0xd2, 0xc3, 0x50, 0xa4, 0xdb, 0x8a, 0x17, 0xda, 0x7e, 0xec, 0x40,
	0x32, 0xb6, 0x66, 0xb4, 0x6a, 0xa4, 0x81, 0x26, 0xcc, 0x62, 0x10, 0x52, 0xd5, 0x68, 0x31, 0xeb,
	0x50, 0x23, 0x4d, 0xa5, 0x5d, 0x32, 0xf3, 0x59, 0x3d, 0xa4, 0x5b, 0xe8, 0x3b, 0xa3, 0x7c, 0xaf,
	0x34, 0x49, 0xbb, 0x64, 0x96, 0xd1, 0x77, 0x32, 0x17, 0xb5, 0x41, 0xcb, 0x37, 0x10, 0x79, 0x93,
	0xbb, 0x91, 0x8d, 0x0e, 0xd4, 0x0a, 0x2b, 0x06, 0x4d, 0xa0, 0x3e, 0x3a, 0xd0, 0x79, 0x55, 0x68,
	0x31, 0x67, 0xbb, 0xb4, 0x30, 0x00, 0xa9, 0x36, 0xf5, 0xb5, 0x33, 0xf5, 0xb5, 0x56, 0xda, 0xc1,
	0x37, 0xc6, 0x00, 0xec, 0x08, 0x64, 0xeb, 0x68, 0x31, 0x27, 0x67, 0x8b, 0x39, 0x79, 0xf8, 0xf3,
	0xf8, 0xfe, 0xf1, 0xa4, 0xec, 0xb7, 0x76, 0x58, 0xca, 0x60, 0x59, 0xcd, 0x53, 0x72, 0xa2, 0x5e,
	0xd3, 0x7f, 0x17, 0xdc, 0xb1, 0x24, 0xfc, 0x66, 0x56, 0x67, 0x73, 0xd6, 0x15, 0xfd, 0x6b, 0x82,
	0xf8, 0xd9, 0x59, 0xf5, 0x24, 0x41, 0xdb, 0x98, 0xd0, 0xbb, 0xa7, 0xbb, 0x36, 0x06, 0xeb, 0xda,
	0x5e, 0x25, 0xb3, 0x37, 0x96, 0x8f, 0x7b, 0x4e, 0x0c, 0x72, 0x79, 0xec, 0x7a, 0x72, 0x1a, 0x8f,
	0x75, 0x1b, 0x03, 0x96, 0xff, 0x9c, 0xe5, 0x76, 0x1c, 0x4f, 0x98, 0x8b, 0x99, 0xfb, 0x27, 0x21,
	0xcf, 0x4a, 0xa1, 0x6f, 0xf4, 0x5e, 0x94, 0xff, 0xdd, 0x04, 0x7a, 0x53, 0xf6, 0xba, 0x89, 0x60,
	0xb8, 0xb2, 0x1b, 0xa6, 0xf8, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x2d, 0xb0, 0x4c, 0xa3,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PasswordClient is the client API for Password service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PasswordClient interface {
	// Set account password.
	Set(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Secret, error)
	// Update account password.
	Update(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Secret, error)
	// Reset account password.
	Reset(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Secret, error)
}

type passwordClient struct {
	cc *grpc.ClientConn
}

func NewPasswordClient(cc *grpc.ClientConn) PasswordClient {
	return &passwordClient{cc}
}

func (c *passwordClient) Set(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/appootb.account.Password/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordClient) Update(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/appootb.account.Password/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordClient) Reset(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Secret, error) {
	out := new(Secret)
	err := c.cc.Invoke(ctx, "/appootb.account.Password/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordServer is the server API for Password service.
type PasswordServer interface {
	// Set account password.
	Set(context.Context, *PasswordRequest) (*Secret, error)
	// Update account password.
	Update(context.Context, *PasswordRequest) (*Secret, error)
	// Reset account password.
	Reset(context.Context, *PasswordRequest) (*Secret, error)
}

// UnimplementedPasswordServer can be embedded to have forward compatible implementations.
type UnimplementedPasswordServer struct {
}

func (*UnimplementedPasswordServer) Set(ctx context.Context, req *PasswordRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedPasswordServer) Update(ctx context.Context, req *PasswordRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPasswordServer) Reset(ctx context.Context, req *PasswordRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}

func RegisterPasswordServer(s *grpc.Server, srv PasswordServer) {
	s.RegisterService(&_Password_serviceDesc, srv)
}

func _Password_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Password/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServer).Set(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Password_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Password/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServer).Update(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Password_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.account.Password/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServer).Reset(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Password_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.account.Password",
	HandlerType: (*PasswordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Password_Set_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Password_Update_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Password_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "password.proto",
}
