// Code generated by protoc-gen-auth. DO NOT EDIT!
// source: profile.proto
package account

import (
	"github.com/appootb/protobuf/go/permission"
	"github.com/appootb/protobuf/go/service"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = permission.TokenLevel_NONE_TOKEN
var _ = service.UnaryServerInterceptor

var _levelProfile = map[string]permission.TokenLevel{
	"/appootb.account.Profile/Get":  permission.TokenLevel_LOW_TOKEN,
	"/appootb.account.Profile/Gets": permission.TokenLevel_LOW_TOKEN,
	"/appootb.account.Profile/Set":  permission.TokenLevel_LOW_TOKEN,
}

// Register scoped server.
func RegisterProfileScopeServer(auth service.Authenticator, impl service.Implementor, srv ProfileServer) error {
	// Register service required token level.
	auth.RegisterServiceTokenLevel(_levelProfile)

	// Register scoped gRPC server.
	for _, grpc := range impl.GetScopedGRPCServer(permission.VisibleScope_DEFAULT_SCOPE) {
		RegisterProfileServer(grpc, srv)
	}
	// Register scoped gateway handler server.
	for _, mux := range impl.GetScopedGatewayMux(permission.VisibleScope_DEFAULT_SCOPE) {
		err := RegisterProfileHandlerServer(impl.Context(), mux, srv)
		if err != nil {
			return err
		}
	}
	return nil
}
