// Code generated by protoc-gen-auth. DO NOT EDIT!
// source: device_token.proto
package notification

import (
	"context"
	"net/http"

	"github.com/appootb/protobuf/go/permission"
	"github.com/appootb/protobuf/go/service"
	"github.com/appootb/protobuf/go/webstream"
	"github.com/golang/protobuf/ptypes/empty"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"golang.org/x/net/websocket"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = http.StatusOK
var _ = runtime.String
var _ = context.TODO()
var _ = grpc.ServiceDesc{}
var _ = webstream.WebStream{}
var _ = websocket.UnknownFrame
var _ = permission.Subject_NONE
var _ = service.UnaryServerInterceptor

var _deviceTokenServiceSubjects = map[string][]permission.Subject{
	"/appootb.notification.DeviceToken/Update": {
		permission.Subject_WEB,
		permission.Subject_PC,
		permission.Subject_MOBILE,
	},
}

type wrapperDeviceTokenServer struct {
	DeviceTokenServer
	service.Implementor
}

func (w *wrapperDeviceTokenServer) Update(ctx context.Context, req *UniqueToken) (*empty.Empty, error) {
	if w.UnaryInterceptor() == nil {
		return w.DeviceTokenServer.Update(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.DeviceTokenServer,
		FullMethod: "/appootb.notification.DeviceToken/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.DeviceTokenServer.Update(ctx, req.(*UniqueToken))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*empty.Empty), nil
}

// Register scoped server.
func RegisterDeviceTokenScopeServer(component string, auth service.Authenticator, impl service.Implementor, srv DeviceTokenServer) error {
	// Register service required subjects.
	auth.RegisterServiceSubjects(component, _deviceTokenServiceSubjects)

	// Register scoped gRPC server.
	for _, gRPC := range impl.GetGRPCServer(permission.VisibleScope_CLIENT) {
		RegisterDeviceTokenServer(gRPC, srv)
	}
	// Register scoped gateway handler server.
	wrapper := wrapperDeviceTokenServer{
		DeviceTokenServer: srv,
		Implementor:       impl,
	}
	for _, mux := range impl.GetGatewayMux(permission.VisibleScope_CLIENT) {
		// Register gateway handler.
		if err := RegisterDeviceTokenHandlerServer(impl.Context(), mux, &wrapper); err != nil {
			return err
		}
	}

	return nil
}
