// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: inner_hash_field.proto

package counter

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _inner_hash_field_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on HashFieldKey with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *HashFieldKey) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Product

	// no validation rules for Type

	// no validation rules for RelateId

	// no validation rules for Field

	// no validation rules for Value

	return nil
}

// HashFieldKeyValidationError is the validation error returned by
// HashFieldKey.Validate if the designated constraints aren't met.
type HashFieldKeyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashFieldKeyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashFieldKeyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashFieldKeyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashFieldKeyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashFieldKeyValidationError) ErrorName() string { return "HashFieldKeyValidationError" }

// Error satisfies the builtin error interface
func (e HashFieldKeyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashFieldKey.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashFieldKeyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashFieldKeyValidationError{}
