// Code generated by protoc-gen-auth. DO NOT EDIT!
// source: inner_key.proto
package counter

import (
	"context"
	"net/http"

	"github.com/appootb/protobuf/go/permission"
	"github.com/appootb/protobuf/go/service"
	"github.com/appootb/protobuf/go/webstream"
	"github.com/golang/protobuf/ptypes/empty"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"golang.org/x/net/websocket"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = http.StatusOK
var _ = runtime.String
var _ = context.TODO()
var _ = grpc.ServiceDesc{}
var _ = webstream.WebStream{}
var _ = websocket.UnknownFrame
var _ = permission.Subject_NONE
var _ = service.UnaryServerInterceptor

var _innerKeyServiceSubjects = map[string][]permission.Subject{
	"/appootb.counter.InnerKey/Get": {
		permission.Subject_SERVER,
	},
	"/appootb.counter.InnerKey/Gets": {
		permission.Subject_SERVER,
	},
	"/appootb.counter.InnerKey/Increase": {
		permission.Subject_SERVER,
	},
	"/appootb.counter.InnerKey/MultiIncrease": {
		permission.Subject_SERVER,
	},
	"/appootb.counter.InnerKey/Set": {
		permission.Subject_SERVER,
	},
	"/appootb.counter.InnerKey/Sets": {
		permission.Subject_SERVER,
	},
}

type wrapperInnerKeyServer struct {
	InnerKeyServer
	service.Implementor
}

func (w *wrapperInnerKeyServer) Increase(ctx context.Context, req *Key) (*Key, error) {
	if w.UnaryInterceptor() == nil {
		return w.InnerKeyServer.Increase(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.InnerKeyServer,
		FullMethod: "/appootb.counter.InnerKey/Increase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.InnerKeyServer.Increase(ctx, req.(*Key))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*Key), nil
}

func (w *wrapperInnerKeyServer) MultiIncrease(ctx context.Context, req *Keys) (*Keys, error) {
	if w.UnaryInterceptor() == nil {
		return w.InnerKeyServer.MultiIncrease(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.InnerKeyServer,
		FullMethod: "/appootb.counter.InnerKey/MultiIncrease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.InnerKeyServer.MultiIncrease(ctx, req.(*Keys))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*Keys), nil
}

func (w *wrapperInnerKeyServer) Get(ctx context.Context, req *Key) (*Key, error) {
	if w.UnaryInterceptor() == nil {
		return w.InnerKeyServer.Get(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.InnerKeyServer,
		FullMethod: "/appootb.counter.InnerKey/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.InnerKeyServer.Get(ctx, req.(*Key))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*Key), nil
}

func (w *wrapperInnerKeyServer) Gets(ctx context.Context, req *Keys) (*Keys, error) {
	if w.UnaryInterceptor() == nil {
		return w.InnerKeyServer.Gets(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.InnerKeyServer,
		FullMethod: "/appootb.counter.InnerKey/Gets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.InnerKeyServer.Gets(ctx, req.(*Keys))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*Keys), nil
}

func (w *wrapperInnerKeyServer) Set(ctx context.Context, req *Key) (*empty.Empty, error) {
	if w.UnaryInterceptor() == nil {
		return w.InnerKeyServer.Set(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.InnerKeyServer,
		FullMethod: "/appootb.counter.InnerKey/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.InnerKeyServer.Set(ctx, req.(*Key))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*empty.Empty), nil
}

func (w *wrapperInnerKeyServer) Sets(ctx context.Context, req *Keys) (*empty.Empty, error) {
	if w.UnaryInterceptor() == nil {
		return w.InnerKeyServer.Sets(ctx, req)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w.InnerKeyServer,
		FullMethod: "/appootb.counter.InnerKey/Sets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.InnerKeyServer.Sets(ctx, req.(*Keys))
	}
	resp, err := w.UnaryInterceptor()(ctx, req, info, handler)
	if err != nil {
		return nil, err
	}
	return resp.(*empty.Empty), nil
}

// Register scoped server.
func RegisterInnerKeyScopeServer(component string, auth service.Authenticator, impl service.Implementor, srv InnerKeyServer) error {
	// Register service required subjects.
	auth.RegisterServiceSubjects(component, _innerKeyServiceSubjects)

	// Register scoped gRPC server.
	for _, gRPC := range impl.GetGRPCServer(permission.VisibleScope_SERVER) {
		RegisterInnerKeyServer(gRPC, srv)
	}
	// Register scoped gateway handler server.
	wrapper := wrapperInnerKeyServer{
		InnerKeyServer: srv,
		Implementor:    impl,
	}
	for _, mux := range impl.GetGatewayMux(permission.VisibleScope_SERVER) {
		// Register gateway handler.
		if err := RegisterInnerKeyHandlerServer(impl.Context(), mux, &wrapper); err != nil {
			return err
		}
	}

	return nil
}
