// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: inner_hash.proto

package counter

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _inner_hash_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on HashField with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HashField) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Product

	// no validation rules for Type

	// no validation rules for RelateId

	// no validation rules for Field

	// no validation rules for Value

	return nil
}

// HashFieldValidationError is the validation error returned by
// HashField.Validate if the designated constraints aren't met.
type HashFieldValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashFieldValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashFieldValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashFieldValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashFieldValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashFieldValidationError) ErrorName() string { return "HashFieldValidationError" }

// Error satisfies the builtin error interface
func (e HashFieldValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashField.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashFieldValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashFieldValidationError{}

// Validate checks the field values on HashFields with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HashFields) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Product

	// no validation rules for Type

	// no validation rules for RelateId

	// no validation rules for Values

	return nil
}

// HashFieldsValidationError is the validation error returned by
// HashFields.Validate if the designated constraints aren't met.
type HashFieldsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashFieldsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashFieldsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashFieldsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashFieldsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashFieldsValidationError) ErrorName() string { return "HashFieldsValidationError" }

// Error satisfies the builtin error interface
func (e HashFieldsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashFields.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashFieldsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashFieldsValidationError{}

// Validate checks the field values on HashKeys with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HashKeys) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Product

	// no validation rules for Type

	return nil
}

// HashKeysValidationError is the validation error returned by
// HashKeys.Validate if the designated constraints aren't met.
type HashKeysValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashKeysValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashKeysValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashKeysValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashKeysValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashKeysValidationError) ErrorName() string { return "HashKeysValidationError" }

// Error satisfies the builtin error interface
func (e HashKeysValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashKeys.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashKeysValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashKeysValidationError{}

// Validate checks the field values on HashValue with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HashValue) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for FieldValues

	return nil
}

// HashValueValidationError is the validation error returned by
// HashValue.Validate if the designated constraints aren't met.
type HashValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashValueValidationError) ErrorName() string { return "HashValueValidationError" }

// Error satisfies the builtin error interface
func (e HashValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashValueValidationError{}

// Validate checks the field values on HashValues with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HashValues) Validate() error {
	if m == nil {
		return nil
	}

	for key, val := range m.GetValues() {
		_ = val

		// no validation rules for Values[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HashValuesValidationError{
					field:  fmt.Sprintf("Values[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// HashValuesValidationError is the validation error returned by
// HashValues.Validate if the designated constraints aren't met.
type HashValuesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashValuesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashValuesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashValuesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashValuesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashValuesValidationError) ErrorName() string { return "HashValuesValidationError" }

// Error satisfies the builtin error interface
func (e HashValuesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashValues.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashValuesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashValuesValidationError{}
