// Code generated by protoc-gen-go. DO NOT EDIT.
// source: include.proto

package relation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Relation apply request.
type ApplyRequest struct {
	Target               *uint64  `protobuf:"varint,1,req,name=target" json:"target,omitempty"`
	Reason               *string  `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{0}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetTarget() uint64 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func (m *ApplyRequest) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

// Relation status request.
type StatusRequest struct {
	Target               *uint64  `protobuf:"varint,1,req,name=target" json:"target,omitempty"`
	Ids                  []uint64 `protobuf:"varint,2,rep,name=ids" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{1}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetTarget() uint64 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func (m *StatusRequest) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

// Relation status response.
type StatusResponse struct {
	State                map[uint64]bool `protobuf:"bytes,1,rep,name=state" json:"state,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1eef7b97e24a48e, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetState() map[uint64]bool {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "appootb.relation.ApplyRequest")
	proto.RegisterType((*StatusRequest)(nil), "appootb.relation.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "appootb.relation.StatusResponse")
	proto.RegisterMapType((map[uint64]bool)(nil), "appootb.relation.StatusResponse.StateEntry")
}

func init() { proto.RegisterFile("include.proto", fileDescriptor_f1eef7b97e24a48e) }

var fileDescriptor_f1eef7b97e24a48e = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x99, 0x49, 0xfb, 0xd3, 0x7f, 0x6a, 0xa5, 0x84, 0x52, 0x82, 0xab, 0xd0, 0x8d, 0x01,
	0x21, 0x01, 0x57, 0xd5, 0x85, 0xd0, 0x16, 0xc1, 0x65, 0x19, 0x77, 0xd2, 0xcd, 0xb4, 0xbd, 0xd6,
	0xd0, 0x64, 0xee, 0x98, 0xb9, 0x23, 0x64, 0xe1, 0x23, 0xf8, 0x12, 0x2e, 0x7d, 0x14, 0x9f, 0xc8,
	0xa5, 0x24, 0x4d, 0x10, 0x75, 0xe1, 0x6e, 0xce, 0x99, 0xf9, 0xee, 0x99, 0x7b, 0xc4, 0x20, 0xd5,
	0x9b, 0xcc, 0x6d, 0x21, 0x36, 0x05, 0x12, 0xfa, 0x43, 0x65, 0x0c, 0x22, 0xad, 0xe3, 0x02, 0x32,
	0x45, 0x29, 0xea, 0xc9, 0x95, 0x38, 0x9a, 0x19, 0x93, 0x95, 0x12, 0x1e, 0x1d, 0x58, 0xf2, 0xc7,
	0xe2, 0x1f, 0xa9, 0x62, 0x07, 0x14, 0xb0, 0x90, 0x47, 0x1d, 0xd9, 0xa8, 0xca, 0x2f, 0x40, 0x59,
	0xd4, 0x01, 0x0f, 0x59, 0xf4, 0x5f, 0x36, 0x6a, 0x72, 0x21, 0x06, 0xb7, 0xa4, 0xc8, 0xd9, 0xbf,
	0x06, 0x0c, 0x85, 0x97, 0x6e, 0x6d, 0xc0, 0x43, 0x2f, 0xea, 0xc8, 0xea, 0x38, 0x79, 0x61, 0xe2,
	0xb8, 0x65, 0xad, 0x41, 0x6d, 0xc1, 0x9f, 0x89, 0xae, 0x25, 0x45, 0x10, 0xb0, 0xd0, 0x8b, 0xfa,
	0xe7, 0x67, 0xf1, 0xcf, 0xff, 0xc6, 0xdf, 0x81, 0x5a, 0xc2, 0xb5, 0xa6, 0xa2, 0x94, 0x07, 0xf2,
	0x64, 0x2a, 0xc4, 0x97, 0x59, 0xa5, 0xee, 0xa1, 0x0c, 0x58, 0xc8, 0xaa, 0xd4, 0x3d, 0x94, 0xfe,
	0x48, 0x74, 0x9f, 0x54, 0xe6, 0xa0, 0xde, 0xa3, 0x27, 0x0f, 0xe2, 0x92, 0x4f, 0xd9, 0xfc, 0x59,
	0x8c, 0x36, 0x98, 0xff, 0x8a, 0x9c, 0xf7, 0x17, 0x98, 0xe7, 0xa8, 0x97, 0x55, 0x83, 0x37, 0x6c,
	0xc9, 0xee, 0x4e, 0x77, 0x29, 0x3d, 0xb8, 0x75, 0xbc, 0xc1, 0x3c, 0x69, 0x5e, 0x27, 0x75, 0xbf,
	0x6b, 0x77, 0x9f, 0xec, 0x30, 0x69, 0xc9, 0x0f, 0xc6, 0x5e, 0xb9, 0xb7, 0x58, 0xce, 0xdf, 0x78,
	0x4f, 0x36, 0xde, 0x3b, 0x1f, 0xcf, 0x0e, 0xc8, 0xaa, 0x1e, 0xb8, 0x6a, 0x2f, 0x3e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x2d, 0x58, 0x3a, 0xc6, 0xab, 0x01, 0x00, 0x00,
}
