// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_follow.proto

package relation

import (
	context "context"
	fmt "fmt"
	common "github.com/appootb/protobuf/go/common"
	_ "github.com/appootb/protobuf/go/permission"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("inner_follow.proto", fileDescriptor_78ba93e818bd2dde) }

var fileDescriptor_78ba93e818bd2dde = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0x49, 0xfe, 0xff, 0x83, 0xa6, 0x08, 0x65, 0x11, 0xc1, 0x20, 0x52, 0xbc, 0x94, 0x22,
	0x64, 0xd1, 0x37, 0xb0, 0x42, 0x31, 0xb7, 0x52, 0xf1, 0x22, 0xc5, 0x92, 0x26, 0xdb, 0x38, 0x90,
	0xcc, 0xc4, 0xcc, 0x46, 0x11, 0x29, 0x48, 0xef, 0x9e, 0xbc, 0x78, 0xf6, 0xe8, 0xa3, 0x78, 0xf5,
	0x15, 0x7c, 0x08, 0x8f, 0xd2, 0xdd, 0xa4, 0x88, 0x82, 0x17, 0x6f, 0xcb, 0x7c, 0x33, 0xdf, 0xf7,
	0xe3, 0x5b, 0x4f, 0x00, 0xa2, 0x2a, 0x27, 0x33, 0xca, 0x32, 0xba, 0x09, 0x8a, 0x92, 0x34, 0x89,
	0x76, 0x54, 0x14, 0x44, 0x7a, 0x1a, 0x94, 0x2a, 0x8b, 0x34, 0x10, 0xfa, 0xbb, 0xf5, 0x44, 0xc6,
	0x94, 0xe7, 0x84, 0xb2, 0x42, 0xb8, 0xaa, 0xd4, 0x04, 0x12, 0x7b, 0xe1, 0x77, 0x1a, 0xbd, 0x50,
	0x65, 0x0e, 0xcc, 0x40, 0x28, 0x59, 0x95, 0xd7, 0x10, 0xab, 0x7a, 0x63, 0x27, 0x25, 0x4a, 0x33,
	0x25, 0xa3, 0x02, 0x64, 0x84, 0x48, 0xda, 0x18, 0x73, 0xad, 0x6e, 0x00, 0xc6, 0x59, 0x95, 0xd4,
	0xcb, 0x87, 0x0f, 0xae, 0xd7, 0x0a, 0x97, 0x5c, 0x03, 0x83, 0x25, 0xe6, 0x5e, 0x2b, 0x64, 0xfb,
	0x06, 0x4c, 0xc5, 0x76, 0xd0, 0x00, 0x5a, 0x9c, 0xe0, 0xcc, 0xe0, 0x84, 0x09, 0xfb, 0x9d, 0xe0,
	0x3b, 0x7b, 0x70, 0xaa, 0x23, 0x5d, 0xf1, 0x48, 0x71, 0x41, 0xc8, 0x6a, 0xef, 0x60, 0xf1, 0xf6,
	0xfe, 0xe8, 0xee, 0x8b, 0x9e, 0x6c, 0x36, 0xa4, 0xa9, 0x40, 0xda, 0x0a, 0x24, 0x70, 0x5d, 0x06,
	0x60, 0x2a, 0xef, 0x20, 0xe1, 0xb9, 0xb8, 0xf5, 0xd6, 0x43, 0x1e, 0x94, 0xa0, 0x30, 0xe1, 0xbf,
	0x85, 0x4b, 0x13, 0xde, 0x13, 0xdd, 0x5f, 0xc2, 0x6d, 0x8e, 0x8d, 0xf6, 0xff, 0x3f, 0x5d, 0xdc,
	0xbb, 0xfd, 0x85, 0xe3, 0x6d, 0xc6, 0x94, 0xff, 0xb0, 0xef, 0xb7, 0xbf, 0xb4, 0x34, 0x5c, 0x56,
	0x77, 0xe2, 0x0c, 0x9d, 0xf3, 0x6e, 0x0a, 0xfa, 0xb2, 0x32, 0x80, 0x72, 0xf5, 0x31, 0x4b, 0x75,
	0x5a, 0xcd, 0x64, 0x4a, 0xab, 0xec, 0x0f, 0xc7, 0x79, 0x76, 0xff, 0x1d, 0x0f, 0xfb, 0x2f, 0xee,
	0xda, 0xa8, 0x9e, 0xbd, 0xba, 0x5b, 0x47, 0xf6, 0x64, 0x6c, 0x0c, 0xc7, 0x8d, 0xf0, 0x19, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x58, 0xb5, 0x0a, 0x2a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InnerFollowClient is the client API for InnerFollow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnerFollowClient interface {
	// Check following.
	IsFollowing(ctx context.Context, in *common.UniqueIds, opts ...grpc.CallOption) (*StatusResponse, error)
	// Check friends.
	IsFriends(ctx context.Context, in *common.UniqueIds, opts ...grpc.CallOption) (*StatusResponse, error)
}

type innerFollowClient struct {
	cc *grpc.ClientConn
}

func NewInnerFollowClient(cc *grpc.ClientConn) InnerFollowClient {
	return &innerFollowClient{cc}
}

func (c *innerFollowClient) IsFollowing(ctx context.Context, in *common.UniqueIds, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/appootb.relation.InnerFollow/IsFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innerFollowClient) IsFriends(ctx context.Context, in *common.UniqueIds, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/appootb.relation.InnerFollow/IsFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerFollowServer is the server API for InnerFollow service.
type InnerFollowServer interface {
	// Check following.
	IsFollowing(context.Context, *common.UniqueIds) (*StatusResponse, error)
	// Check friends.
	IsFriends(context.Context, *common.UniqueIds) (*StatusResponse, error)
}

// UnimplementedInnerFollowServer can be embedded to have forward compatible implementations.
type UnimplementedInnerFollowServer struct {
}

func (*UnimplementedInnerFollowServer) IsFollowing(ctx context.Context, req *common.UniqueIds) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFollowing not implemented")
}
func (*UnimplementedInnerFollowServer) IsFriends(ctx context.Context, req *common.UniqueIds) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFriends not implemented")
}

func RegisterInnerFollowServer(s *grpc.Server, srv InnerFollowServer) {
	s.RegisterService(&_InnerFollow_serviceDesc, srv)
}

func _InnerFollow_IsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UniqueIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerFollowServer).IsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.relation.InnerFollow/IsFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerFollowServer).IsFollowing(ctx, req.(*common.UniqueIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnerFollow_IsFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UniqueIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerFollowServer).IsFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appootb.relation.InnerFollow/IsFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerFollowServer).IsFriends(ctx, req.(*common.UniqueIds))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerFollow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appootb.relation.InnerFollow",
	HandlerType: (*InnerFollowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsFollowing",
			Handler:    _InnerFollow_IsFollowing_Handler,
		},
		{
			MethodName: "IsFriends",
			Handler:    _InnerFollow_IsFriends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_follow.proto",
}
